import type { Locale } from '@/i18n/config';

const pt = {
  tagline: 'Odontologia estética',
  navTreatments: 'Tratamentos',
  navSimulator: 'Simulador',
  navTeam: 'Equipe',
  book: 'Agendar avaliação',
  heroEyebrow: 'Botafogo · Rio de Janeiro',
  heroTitleA: 'Um sorriso que é',
  heroTitleEm: 'a sua cara',
  heroLead:
    'Clareamento, lentes, alinhadores invisíveis e implantes com planejamento digital. Você vê o resultado antes de começar.',
  trySimulator: 'Testar o simulador',
  heroAlt: 'Consultório da Lumi Odontologia',
  heroBadges: [
    { title: 'Escaneamento 3D', desc: 'sem moldeira' },
    { title: 'Seg–Sáb', desc: '8h às 20h' },
    { title: 'Sedação', desc: 'para quem tem medo' },
  ],
  floatingTitle: 'Planejamento digital',
  floatingDesc: 'Seu sorriso simulado antes da primeira sessão.',
  simEyebrow: 'Simulador',
  simTitleA: 'Arraste e veja',
  simTitleEm: 'o seu novo tom',
  simLead: 'Mova o controle para comparar os tons da escala de cor usada no consultório.',
  simSlider: 'Nível de clareamento',
  simShade: 'Tom',
  simLighter: (n: number): string => (n === 0 ? 'Tom de partida' : `${n} ${n === 1 ? 'tom mais claro' : 'tons mais claros'}`),
  simBefore: 'Antes',
  simAfter: 'Depois',
  simNote: 'Simulação ilustrativa. A indicação e o resultado dependem de avaliação clínica.',
  treatmentsEyebrow: 'Tratamentos',
  treatmentsTitle: 'Do check-up à reabilitação completa.',
  treatments: [
    {
      id: 'estetica',
      name: 'Estética do sorriso',
      lead: 'Clareamento supervisionado e lentes de contato dentais com planejamento digital do sorriso.',
      bullets: ['Clareamento em consultório e caseiro', 'Lentes e facetas em cerâmica', 'Planejamento digital (DSD)', 'Gengivoplastia'],
      duration: '2 a 6 semanas',
    },
    {
      id: 'orto',
      name: 'Ortodontia',
      lead: 'Alinhadores invisíveis e aparelhos estéticos para todas as idades.',
      bullets: ['Alinhadores transparentes', 'Aparelho autoligado', 'Escaneamento intraoral 3D', 'Contenção pós-tratamento'],
      duration: '6 a 18 meses',
    },
    {
      id: 'implantes',
      name: 'Implantes',
      lead: 'Reabilitação com implantes e próteses fixas, com cirurgia guiada por tomografia.',
      bullets: ['Implante unitário', 'Protocolo fixo', 'Cirurgia guiada', 'Enxerto ósseo'],
      duration: '3 a 6 meses',
    },
    {
      id: 'prevencao',
      name: 'Prevenção',
      lead: 'Check-up, limpeza profissional e acompanhamento para toda a família.',
      bullets: ['Limpeza e profilaxia', 'Odontopediatria', 'Clareamento de manutenção', 'Placa para bruxismo'],
      duration: '1 sessão',
    },
  ],
  durationLabel: 'Duração média',
  wantThis: 'Quero agendar',
  teamEyebrow: 'Equipe',
  teamTitle: 'Quem cuida do seu sorriso.',
  team: [
    { name: 'Dra. Helena Prado', role: 'Diretora clínica', specialty: 'Estética e prótese' },
    { name: 'Dr. Caio Nogueira', role: 'Ortodontista', specialty: 'Alinhadores invisíveis' },
    { name: 'Dra. Marina Lopes', role: 'Implantodontista', specialty: 'Cirurgia guiada' },
  ],
  bookingEyebrow: 'Agendamento',
  bookingTitle: 'Sua avaliação em 3 passos.',
  bookingLead: 'Escolha o tratamento, o melhor dia e deixe seu contato. A confirmação chega pelo WhatsApp.',
  stepOf: (s: number) => `Passo ${s} de 3`,
  step1: 'Qual tratamento te interessa?',
  notSure: 'Ainda não sei',
  step2: 'Quando fica melhor pra você?',
  periods: { morning: 'Manhã', afternoon: 'Tarde', evening: 'Noite' },
  step3: 'Como falamos com você?',
  name: 'Nome',
  namePlaceholder: 'Seu nome completo',
  back: 'Voltar',
  next: 'Continuar',
  confirm: 'Confirmar agendamento',
  errors: {
    treatment: 'Escolha uma opção.',
    slot: 'Escolha um dia e um período.',
    name: 'Nome é obrigatório.',
    phone: 'Telefone incompleto.',
  },
  doneTitle: (name: string) => `Tudo certo, ${name}!`,
  doneText: 'Sua pré-reserva foi registrada. Este é um demo — nenhum horário foi realmente agendado.',
  summaryTreatment: 'Tratamento',
  summaryWhen: 'Quando',
  newBooking: 'Novo agendamento',
  compliance: 'Responsável técnica: Dra. Helena Prado · CRO-RJ 45.210. Imagens meramente ilustrativas.',
  demoBy: 'Demo por MX Studio Web',
};

type LumiText = typeof pt;

const en: LumiText = {
  tagline: 'Cosmetic dentistry',
  navTreatments: 'Treatments',
  navSimulator: 'Simulator',
  navTeam: 'Team',
  book: 'Book an assessment',
  heroEyebrow: 'Botafogo · Rio de Janeiro',
  heroTitleA: 'A smile that looks',
  heroTitleEm: 'just like you',
  heroLead:
    'Whitening, veneers, clear aligners and implants with digital planning. You see the result before you start.',
  trySimulator: 'Try the simulator',
  heroAlt: 'Lumi Odontologia dental office',
  heroBadges: [
    { title: '3D scanning', desc: 'no messy molds' },
    { title: 'Mon–Sat', desc: '8am to 8pm' },
    { title: 'Sedation', desc: 'for anxious patients' },
  ],
  floatingTitle: 'Digital planning',
  floatingDesc: 'Your smile simulated before the first session.',
  simEyebrow: 'Simulator',
  simTitleA: 'Drag and see',
  simTitleEm: 'your new shade',
  simLead: 'Move the slider to compare shades from the color scale we use in the office.',
  simSlider: 'Whitening level',
  simShade: 'Shade',
  simLighter: (n) => (n === 0 ? 'Starting shade' : `${n} ${n === 1 ? 'shade' : 'shades'} lighter`),
  simBefore: 'Before',
  simAfter: 'After',
  simNote: 'Illustrative simulation. Suitability and results depend on a clinical assessment.',
  treatmentsEyebrow: 'Treatments',
  treatmentsTitle: 'From check-ups to full-mouth rehabilitation.',
  treatments: [
    {
      id: 'estetica',
      name: 'Smile aesthetics',
      lead: 'Supervised whitening and porcelain veneers guided by digital smile design.',
      bullets: ['In-office and take-home whitening', 'Porcelain veneers', 'Digital smile design (DSD)', 'Gum contouring'],
      duration: '2 to 6 weeks',
    },
    {
      id: 'orto',
      name: 'Orthodontics',
      lead: 'Clear aligners and discreet braces for every age.',
      bullets: ['Clear aligners', 'Self-ligating braces', '3D intraoral scanning', 'Post-treatment retainers'],
      duration: '6 to 18 months',
    },
    {
      id: 'implantes',
      name: 'Implants',
      lead: 'Implants and fixed prosthetics with CT-guided surgery.',
      bullets: ['Single-tooth implants', 'Full-arch fixed bridge', 'Guided surgery', 'Bone grafting'],
      duration: '3 to 6 months',
    },
    {
      id: 'prevencao',
      name: 'Prevention',
      lead: 'Check-ups, professional cleaning and follow-up for the whole family.',
      bullets: ['Cleaning and prophylaxis', 'Pediatric dentistry', 'Maintenance whitening', 'Night guard for bruxism'],
      duration: '1 session',
    },
  ],
  durationLabel: 'Average duration',
  wantThis: 'Book this',
  teamEyebrow: 'Team',
  teamTitle: 'The people caring for your smile.',
  team: [
    { name: 'Dr. Helena Prado', role: 'Clinical director', specialty: 'Aesthetics & prosthetics' },
    { name: 'Dr. Caio Nogueira', role: 'Orthodontist', specialty: 'Clear aligners' },
    { name: 'Dr. Marina Lopes', role: 'Implant dentist', specialty: 'Guided surgery' },
  ],
  bookingEyebrow: 'Booking',
  bookingTitle: 'Your assessment in 3 steps.',
  bookingLead: 'Pick a treatment and the best day, then leave your contact. Confirmation arrives on WhatsApp.',
  stepOf: (s) => `Step ${s} of 3`,
  step1: 'Which treatment are you interested in?',
  notSure: 'Not sure yet',
  step2: 'When works best for you?',
  periods: { morning: 'Morning', afternoon: 'Afternoon', evening: 'Evening' },
  step3: 'How can we reach you?',
  name: 'Name',
  namePlaceholder: 'Your full name',
  back: 'Back',
  next: 'Continue',
  confirm: 'Confirm booking',
  errors: {
    treatment: 'Choose an option.',
    slot: 'Pick a day and a time of day.',
    name: 'Name is required.',
    phone: 'Incomplete phone number.',
  },
  doneTitle: (name) => `All set, ${name}!`,
  doneText: 'Your pre-booking was saved. This is a demo — no appointment was actually made.',
  summaryTreatment: 'Treatment',
  summaryWhen: 'When',
  newBooking: 'New booking',
  compliance: 'Lead dentist: Dr. Helena Prado · CRO-RJ 45.210. Images are for illustration only.',
  demoBy: 'Demo by MX Studio Web',
};

const es: LumiText = {
  tagline: 'Odontología estética',
  navTreatments: 'Tratamientos',
  navSimulator: 'Simulador',
  navTeam: 'Equipo',
  book: 'Pedir evaluación',
  heroEyebrow: 'Botafogo · Río de Janeiro',
  heroTitleA: 'Una sonrisa que',
  heroTitleEm: 'se parece a ti',
  heroLead:
    'Blanqueamiento, carillas, alineadores invisibles e implantes con planificación digital. Ves el resultado antes de empezar.',
  trySimulator: 'Probar el simulador',
  heroAlt: 'Consultorio de Lumi Odontologia',
  heroBadges: [
    { title: 'Escaneo 3D', desc: 'sin moldes' },
    { title: 'Lun–Sáb', desc: '8h a 20h' },
    { title: 'Sedación', desc: 'para quien tiene miedo' },
  ],
  floatingTitle: 'Planificación digital',
  floatingDesc: 'Tu sonrisa simulada antes de la primera sesión.',
  simEyebrow: 'Simulador',
  simTitleA: 'Desliza y mira',
  simTitleEm: 'tu nuevo tono',
  simLead: 'Mueve el control para comparar los tonos de la escala de color que usamos en el consultorio.',
  simSlider: 'Nivel de blanqueamiento',
  simShade: 'Tono',
  simLighter: (n) => (n === 0 ? 'Tono inicial' : `${n} ${n === 1 ? 'tono más claro' : 'tonos más claros'}`),
  simBefore: 'Antes',
  simAfter: 'Después',
  simNote: 'Simulación ilustrativa. La indicación y el resultado dependen de una evaluación clínica.',
  treatmentsEyebrow: 'Tratamientos',
  treatmentsTitle: 'Del chequeo a la rehabilitación completa.',
  treatments: [
    {
      id: 'estetica',
      name: 'Estética de la sonrisa',
      lead: 'Blanqueamiento supervisado y carillas con diseño digital de la sonrisa.',
      bullets: ['Blanqueamiento en consulta y en casa', 'Carillas de cerámica', 'Diseño digital (DSD)', 'Gingivoplastia'],
      duration: '2 a 6 semanas',
    },
    {
      id: 'orto',
      name: 'Ortodoncia',
      lead: 'Alineadores invisibles y brackets estéticos para todas las edades.',
      bullets: ['Alineadores transparentes', 'Brackets de autoligado', 'Escaneo intraoral 3D', 'Retenedores'],
      duration: '6 a 18 meses',
    },
    {
      id: 'implantes',
      name: 'Implantes',
      lead: 'Rehabilitación con implantes y prótesis fijas, con cirugía guiada por tomografía.',
      bullets: ['Implante unitario', 'Prótesis fija completa', 'Cirugía guiada', 'Injerto óseo'],
      duration: '3 a 6 meses',
    },
    {
      id: 'prevencao',
      name: 'Prevención',
      lead: 'Chequeo, limpieza profesional y seguimiento para toda la familia.',
      bullets: ['Limpieza y profilaxis', 'Odontopediatría', 'Blanqueamiento de mantenimiento', 'Férula para bruxismo'],
      duration: '1 sesión',
    },
  ],
  durationLabel: 'Duración media',
  wantThis: 'Quiero reservar',
  teamEyebrow: 'Equipo',
  teamTitle: 'Quién cuida de tu sonrisa.',
  team: [
    { name: 'Dra. Helena Prado', role: 'Directora clínica', specialty: 'Estética y prótesis' },
    { name: 'Dr. Caio Nogueira', role: 'Ortodoncista', specialty: 'Alineadores invisibles' },
    { name: 'Dra. Marina Lopes', role: 'Implantóloga', specialty: 'Cirugía guiada' },
  ],
  bookingEyebrow: 'Reserva',
  bookingTitle: 'Tu evaluación en 3 pasos.',
  bookingLead: 'Elige el tratamiento y el mejor día, y déjanos tu contacto. La confirmación llega por WhatsApp.',
  stepOf: (s) => `Paso ${s} de 3`,
  step1: '¿Qué tratamiento te interesa?',
  notSure: 'Aún no lo sé',
  step2: '¿Cuándo te viene mejor?',
  periods: { morning: 'Mañana', afternoon: 'Tarde', evening: 'Noche' },
  step3: '¿Cómo te contactamos?',
  name: 'Nombre',
  namePlaceholder: 'Tu nombre completo',
  back: 'Volver',
  next: 'Continuar',
  confirm: 'Confirmar reserva',
  errors: {
    treatment: 'Elige una opción.',
    slot: 'Elige un día y una franja horaria.',
    name: 'El nombre es obligatorio.',
    phone: 'Teléfono incompleto.',
  },
  doneTitle: (name) => `¡Listo, ${name}!`,
  doneText: 'Tu prerreserva quedó registrada. Esto es una demo: no se reservó ningún horario.',
  summaryTreatment: 'Tratamiento',
  summaryWhen: 'Cuándo',
  newBooking: 'Nueva reserva',
  compliance: 'Responsable técnica: Dra. Helena Prado · CRO-RJ 45.210. Imágenes meramente ilustrativas.',
  demoBy: 'Demo por MX Studio Web',
};

export const content: Record<Locale, LumiText> = { pt, en, es };
