import type { Locale } from '@/i18n/config';

const pt = {
  tagline: 'Casa de fogo',
  navMenu: 'Menu',
  navBooking: 'Reserva',
  navVisit: 'Visita',
  book: 'Reservar',
  heroAlt: 'Terra Casa de Fogo — brasa',
  heroEyebrow: 'Casa de fogo · Botafogo, Rio de Janeiro',
  heroTitleA: 'Ingredientes,',
  heroTitleEm: 'fogo',
  heroTitleB: 'e tempo.',
  heroLead:
    'Alta gastronomia em torno da brasa. Menu autoral do chef Rafael Menezes, mudando com o que a estação oferece.',
  bookTable: 'Reservar mesa',
  seeMenu: 'Ver o menu',
  stats: [
    { kpi: 'Ter–Dom', label: 'Almoço e jantar' },
    { kpi: '4.9 ★', label: 'Google Business' },
    { kpi: '42 lug.', label: 'Salão + varanda' },
    { kpi: 'Sim', label: 'Aceitamos eventos' },
  ],
  menuEyebrow: 'Menu',
  menuTitleA: 'O que a',
  menuTitleEm: 'brasa',
  menuTitleB: 'oferece hoje.',
  menuNote: 'Menu atualizado semanalmente pelo chef',
  menuTabs: 'Categorias do menu',
  categories: {
    Couvert: 'Couvert',
    Entradas: 'Entradas',
    Principais: 'Principais',
    Sobremesas: 'Sobremesas',
    Bebidas: 'Bebidas',
  },
  tags: { chef: 'Do chef', vegan: 'Vegano', vegetarian: 'Vegetariano' },
  dishes: {
    c1: { name: 'Pães do dia', description: 'Fermentação natural, manteiga de fogo e sal de flor.' },
    c2: { name: 'Azeitonas assadas', description: 'Azeitonas curadas em casa, ervas do quintal.' },
    e1: { name: 'Carpaccio de tomate defumado', description: 'Tomate assado à brasa, ricota fresca, azeite verde.' },
    e2: { name: 'Tartar de carne', description: 'Contrafilé cortado à faca, gema curada, pão de fermentação.' },
    e3: { name: 'Alcachofra de fogo', description: 'Alcachofra cozida no fogo, aioli defumado.' },
    p1: { name: 'Bife de fogo alto', description: 'Ancho maturado 45 dias, brasa direta, farofa de tutano.' },
    p2: { name: 'Peixe do dia à brasa', description: 'Peixe fresco do dia, molho de manteiga queimada.' },
    p3: { name: 'Cordeiro de barro', description: 'Cordeiro assado 8h em forno de barro, purê de abóbora queimada.' },
    p4: { name: 'Risoto de cogumelos silvestres', description: 'Arroz carnaroli, cogumelos assados, queijo curado.' },
    s1: { name: 'Sorvete de leite queimado', description: 'Nossa receita clássica com caramelo de fogo.' },
    s2: { name: 'Torta de banana caramelizada', description: 'Massa folhada, banana no forno, chantilly baunilha.' },
    b1: { name: 'Vinho da casa · taça', description: 'Tempranillo espanhol, seleção do sommelier.' },
    b2: { name: 'Coquetel Terra', description: 'Cachaça envelhecida, mel de flor de laranjeira, alecrim.' },
    b3: { name: 'Água mineral', description: 'Com ou sem gás, servida em taça.' },
  },
  bookingEyebrow: 'Reserva',
  bookingTitleA: 'Sua mesa,',
  bookingTitleEm: 'do jeito',
  bookingTitleB: 'que você quiser.',
  bookingLead:
    'Reservamos até 20 pessoas. Grupos maiores: nos escreva pelo WhatsApp. Cancelamento gratuito até 4 horas antes.',
  hours: 'Ter a Sex: 19h–23h · Sáb e Dom: 12h–15h e 19h–23h',
  reservedTitle: 'Mesa reservada!',
  reservedText: (name: string) => `Obrigado, ${name}. Sua mesa está confirmada.`,
  date: 'Data',
  time: 'Horário',
  people: 'Pessoas',
  reservedNote:
    'Vamos confirmar por WhatsApp em até 10 min. Este é um demo, nenhuma mesa foi realmente reservada.',
  newBooking: 'Nova reserva',
  stepDate: '1 · Data',
  prevWeek: 'Semana anterior',
  nextWeek: 'Próxima semana',
  stepTime: (period: string) => `2 · Horário · ${period}`,
  periods: { lunch: 'Almoço', dinner: 'Jantar' },
  stepPeople: '3 · Pessoas',
  fewer: 'Menos',
  more: 'Mais',
  person: (n: number): string => (n === 1 ? 'pessoa' : 'pessoas'),
  maxPeople: 'Máx. 20. Grupo maior? Chame no WhatsApp.',
  name: 'Nome',
  namePlaceholder: 'Seu nome completo',
  note: 'Observação (opcional)',
  notePlaceholder: 'Alergias, aniversário, mesa da varanda…',
  confirmBooking: 'Confirmar reserva',
  errors: {
    name: 'Diga seu nome pra reservar.',
    phone: 'Telefone com DDD.',
    time: 'Escolha um horário disponível.',
  },
  close: 'Fechar',
  reviewTitle: 'Confere sua reserva',
  nameLabel: 'Nome: ',
  noteLabel: 'Obs: ',
  change: 'Alterar',
  confirm: 'Confirmar',
  philosophy: 'Filosofia',
  quote: ['"cozinhamos com o que a', 'estação nos entrega,', 'e com fogo."'],
  visitEyebrow: 'Visite',
  visitTitle: 'A casa fica em Botafogo, num casarão de 1928.',
  visitLead: 'Salão principal, varanda coberta e mesa do chef pra 8 pessoas. Estacionamento com valet.',
  spaces: [
    { l: 'Salão', s: '32 lugares' },
    { l: 'Varanda', s: '10 lugares' },
    { l: 'Mesa do chef', s: '8 lugares' },
    { l: 'Valet', s: 'incluso' },
  ],
  address: 'Endereço',
  schedule: [
    { days: 'Ter–Sex', hours: '19h às 23h' },
    { days: 'Sáb e Dom', hours: '12h–15h e 19h–23h' },
  ],
  closed: 'Segunda: fechados',
  demoBy: 'Demo por MX Studio Web',
};

type RestauranteText = typeof pt;

const en: RestauranteText = {
  tagline: 'Wood-fire kitchen',
  navMenu: 'Menu',
  navBooking: 'Book',
  navVisit: 'Visit',
  book: 'Book',
  heroAlt: 'Terra Casa de Fogo — embers',
  heroEyebrow: 'Wood-fire kitchen · Botafogo, Rio de Janeiro',
  heroTitleA: 'Ingredients,',
  heroTitleEm: 'fire',
  heroTitleB: 'and time.',
  heroLead:
    'Fine dining built around the embers. A signature menu by chef Rafael Menezes that changes with what the season brings.',
  bookTable: 'Book a table',
  seeMenu: 'See the menu',
  stats: [
    { kpi: 'Tue–Sun', label: 'Lunch and dinner' },
    { kpi: '4.9 ★', label: 'Google Business' },
    { kpi: '42 seats', label: 'Dining room + terrace' },
    { kpi: 'Yes', label: 'We host events' },
  ],
  menuEyebrow: 'Menu',
  menuTitleA: 'What the',
  menuTitleEm: 'embers',
  menuTitleB: 'have for us today.',
  menuNote: 'Menu updated weekly by the chef',
  menuTabs: 'Menu categories',
  categories: {
    Couvert: 'For the table',
    Entradas: 'Starters',
    Principais: 'Mains',
    Sobremesas: 'Desserts',
    Bebidas: 'Drinks',
  },
  tags: { chef: "Chef's pick", vegan: 'Vegan', vegetarian: 'Vegetarian' },
  dishes: {
    c1: { name: 'Bread of the day', description: 'Naturally leavened, fire-roasted butter and flaky salt.' },
    c2: { name: 'Roasted olives', description: 'House-cured olives, herbs from our garden.' },
    e1: { name: 'Smoked tomato carpaccio', description: 'Ember-roasted tomato, fresh ricotta, green olive oil.' },
    e2: { name: 'Beef tartare', description: 'Hand-cut sirloin, cured yolk, sourdough bread.' },
    e3: { name: 'Fire-roasted artichoke', description: 'Artichoke cooked over the fire, smoked aioli.' },
    p1: { name: 'High-heat steak', description: 'Ribeye aged 45 days, direct embers, bone-marrow farofa.' },
    p2: { name: 'Catch of the day on the embers', description: 'Fresh fish of the day, brown butter sauce.' },
    p3: { name: 'Clay-oven lamb', description: 'Lamb roasted 8 hours in a clay oven, charred pumpkin purée.' },
    p4: { name: 'Wild mushroom risotto', description: 'Carnaroli rice, roasted mushrooms, aged cheese.' },
    s1: { name: 'Burnt milk ice cream', description: 'Our classic recipe with fire caramel.' },
    s2: { name: 'Caramelized banana tart', description: 'Puff pastry, oven-baked banana, vanilla whipped cream.' },
    b1: { name: 'House wine · glass', description: "Spanish Tempranillo, the sommelier's pick." },
    b2: { name: 'Terra cocktail', description: 'Aged cachaça, orange blossom honey, rosemary.' },
    b3: { name: 'Mineral water', description: 'Still or sparkling, served by the glass.' },
  },
  bookingEyebrow: 'Reservations',
  bookingTitleA: 'Your table,',
  bookingTitleEm: 'just the way',
  bookingTitleB: 'you like it.',
  bookingLead:
    'We take bookings for up to 20 guests. Larger groups: message us on WhatsApp. Free cancellation up to 4 hours before.',
  hours: 'Tue–Fri: 7pm–11pm · Sat & Sun: 12pm–3pm and 7pm–11pm',
  reservedTitle: 'Table booked!',
  reservedText: (name) => `Thank you, ${name}. Your table is confirmed.`,
  date: 'Date',
  time: 'Time',
  people: 'Guests',
  reservedNote:
    "We'll confirm on WhatsApp within 10 minutes. This is a demo — no table was actually booked.",
  newBooking: 'New booking',
  stepDate: '1 · Date',
  prevWeek: 'Previous week',
  nextWeek: 'Next week',
  stepTime: (period) => `2 · Time · ${period}`,
  periods: { lunch: 'Lunch', dinner: 'Dinner' },
  stepPeople: '3 · Guests',
  fewer: 'Fewer',
  more: 'More',
  person: (n) => (n === 1 ? 'guest' : 'guests'),
  maxPeople: 'Max. 20. Bigger group? Message us on WhatsApp.',
  name: 'Name',
  namePlaceholder: 'Your full name',
  note: 'Notes (optional)',
  notePlaceholder: 'Allergies, birthday, terrace table…',
  confirmBooking: 'Confirm booking',
  errors: {
    name: 'Tell us your name to book.',
    phone: 'Phone number with area code.',
    time: 'Pick an available time.',
  },
  close: 'Close',
  reviewTitle: 'Review your booking',
  nameLabel: 'Name: ',
  noteLabel: 'Notes: ',
  change: 'Edit',
  confirm: 'Confirm',
  philosophy: 'Philosophy',
  quote: ['"we cook with what', 'the season gives us,', 'and with fire."'],
  visitEyebrow: 'Visit',
  visitTitle: "We're in Botafogo, in a mansion built in 1928.",
  visitLead: "Main dining room, covered terrace and a chef's table for 8. Valet parking.",
  spaces: [
    { l: 'Dining room', s: '32 seats' },
    { l: 'Terrace', s: '10 seats' },
    { l: "Chef's table", s: '8 seats' },
    { l: 'Valet', s: 'included' },
  ],
  address: 'Address',
  schedule: [
    { days: 'Tue–Fri', hours: '7pm to 11pm' },
    { days: 'Sat & Sun', hours: '12pm–3pm and 7pm–11pm' },
  ],
  closed: 'Closed on Mondays',
  demoBy: 'Demo by MX Studio Web',
};

const es: RestauranteText = {
  tagline: 'Cocina de fuego',
  navMenu: 'Menú',
  navBooking: 'Reservas',
  navVisit: 'Visita',
  book: 'Reservar',
  heroAlt: 'Terra Casa de Fogo — brasas',
  heroEyebrow: 'Cocina de fuego · Botafogo, Río de Janeiro',
  heroTitleA: 'Ingredientes,',
  heroTitleEm: 'fuego',
  heroTitleB: 'y tiempo.',
  heroLead:
    'Alta cocina alrededor de las brasas. Menú de autor del chef Rafael Menezes, que cambia con lo que ofrece la temporada.',
  bookTable: 'Reservar mesa',
  seeMenu: 'Ver el menú',
  stats: [
    { kpi: 'Mar–Dom', label: 'Almuerzo y cena' },
    { kpi: '4.9 ★', label: 'Google Business' },
    { kpi: '42 plazas', label: 'Salón + terraza' },
    { kpi: 'Sí', label: 'Aceptamos eventos' },
  ],
  menuEyebrow: 'Menú',
  menuTitleA: 'Lo que las',
  menuTitleEm: 'brasas',
  menuTitleB: 'nos ofrecen hoy.',
  menuNote: 'Menú actualizado cada semana por el chef',
  menuTabs: 'Categorías del menú',
  categories: {
    Couvert: 'Para picar',
    Entradas: 'Entrantes',
    Principais: 'Principales',
    Sobremesas: 'Postres',
    Bebidas: 'Bebidas',
  },
  tags: { chef: 'Del chef', vegan: 'Vegano', vegetarian: 'Vegetariano' },
  dishes: {
    c1: { name: 'Panes del día', description: 'Masa madre, mantequilla de fuego y sal en escamas.' },
    c2: { name: 'Aceitunas asadas', description: 'Aceitunas curadas en casa, hierbas de nuestro huerto.' },
    e1: { name: 'Carpaccio de tomate ahumado', description: 'Tomate asado a la brasa, ricota fresca, aceite de oliva verde.' },
    e2: { name: 'Tartar de ternera', description: 'Lomo cortado a cuchillo, yema curada, pan de masa madre.' },
    e3: { name: 'Alcachofa al fuego', description: 'Alcachofa cocinada al fuego, alioli ahumado.' },
    p1: { name: 'Bife a fuego alto', description: 'Ancho madurado 45 días, brasa directa, farofa de tuétano.' },
    p2: { name: 'Pescado del día a la brasa', description: 'Pescado fresco del día, salsa de mantequilla tostada.' },
    p3: { name: 'Cordero al horno de barro', description: 'Cordero asado 8 horas en horno de barro, puré de calabaza tostada.' },
    p4: { name: 'Risotto de setas silvestres', description: 'Arroz carnaroli, setas asadas, queso curado.' },
    s1: { name: 'Helado de leche tostada', description: 'Nuestra receta clásica con caramelo de fuego.' },
    s2: { name: 'Tarta de plátano caramelizado', description: 'Hojaldre, plátano al horno, nata montada de vainilla.' },
    b1: { name: 'Vino de la casa · copa', description: 'Tempranillo español, selección del sumiller.' },
    b2: { name: 'Cóctel Terra', description: 'Cachaça envejecida, miel de azahar, romero.' },
    b3: { name: 'Agua mineral', description: 'Con o sin gas, servida en copa.' },
  },
  bookingEyebrow: 'Reservas',
  bookingTitleA: 'Tu mesa,',
  bookingTitleEm: 'como',
  bookingTitleB: 'tú prefieras.',
  bookingLead:
    'Reservamos para hasta 20 personas. Grupos más grandes: escríbenos por WhatsApp. Cancelación gratuita hasta 4 horas antes.',
  hours: 'Mar a Vie: 19h–23h · Sáb y Dom: 12h–15h y 19h–23h',
  reservedTitle: '¡Mesa reservada!',
  reservedText: (name) => `Gracias, ${name}. Tu mesa está confirmada.`,
  date: 'Fecha',
  time: 'Hora',
  people: 'Personas',
  reservedNote:
    'Te confirmaremos por WhatsApp en menos de 10 min. Esto es una demo: no se reservó ninguna mesa.',
  newBooking: 'Nueva reserva',
  stepDate: '1 · Fecha',
  prevWeek: 'Semana anterior',
  nextWeek: 'Semana siguiente',
  stepTime: (period) => `2 · Hora · ${period}`,
  periods: { lunch: 'Almuerzo', dinner: 'Cena' },
  stepPeople: '3 · Personas',
  fewer: 'Menos',
  more: 'Más',
  person: (n) => (n === 1 ? 'persona' : 'personas'),
  maxPeople: 'Máx. 20. ¿Grupo más grande? Escríbenos por WhatsApp.',
  name: 'Nombre',
  namePlaceholder: 'Tu nombre completo',
  note: 'Observaciones (opcional)',
  notePlaceholder: 'Alergias, cumpleaños, mesa en la terraza…',
  confirmBooking: 'Confirmar reserva',
  errors: {
    name: 'Dinos tu nombre para reservar.',
    phone: 'Teléfono con código de área.',
    time: 'Elige un horario disponible.',
  },
  close: 'Cerrar',
  reviewTitle: 'Revisa tu reserva',
  nameLabel: 'Nombre: ',
  noteLabel: 'Obs.: ',
  change: 'Cambiar',
  confirm: 'Confirmar',
  philosophy: 'Filosofía',
  quote: ['"cocinamos con lo que', 'la temporada nos da,', 'y con fuego."'],
  visitEyebrow: 'Visítanos',
  visitTitle: 'La casa está en Botafogo, en una casona de 1928.',
  visitLead: 'Salón principal, terraza cubierta y mesa del chef para 8 personas. Servicio de aparcacoches.',
  spaces: [
    { l: 'Salón', s: '32 plazas' },
    { l: 'Terraza', s: '10 plazas' },
    { l: 'Mesa del chef', s: '8 plazas' },
    { l: 'Valet', s: 'incluido' },
  ],
  address: 'Dirección',
  schedule: [
    { days: 'Mar–Vie', hours: '19h a 23h' },
    { days: 'Sáb y Dom', hours: '12h–15h y 19h–23h' },
  ],
  closed: 'Lunes: cerrado',
  demoBy: 'Demo por MX Studio Web',
};

export const content: Record<Locale, RestauranteText> = { pt, en, es };
