import type { Locale } from '@/i18n/config';

const pt = {
  tagline: 'Estética avançada',
  navProtocols: 'Protocolos',
  navQuiz: 'Avaliação',
  navPackages: 'Pacotes',
  book: 'Reservar',
  heroEyebrow: 'Ipanema · Rio de Janeiro',
  heroTitleA: 'Sua pele,',
  heroTitleEm: 'no seu melhor',
  heroTitleB: 'tempo.',
  heroLead:
    'Protocolos personalizados de rosto, corpo e pele, conduzidos por médicas dermatologistas e biomédicas especializadas.',
  startQuiz: 'Fazer avaliação online',
  seeProtocols: 'Ver protocolos',
  heroAlt: 'Sala de procedimentos da Íris',
  heroStats: [
    { kpi: '12', label: 'protocolos exclusivos' },
    { kpi: '4.9', label: 'avaliação no Google' },
    { kpi: '1:1', label: 'plano por paciente' },
  ],
  protocolsEyebrow: 'Protocolos',
  protocolsTitleA: 'Tratamentos pensados',
  protocolsTitleEm: 'para cada área',
  areas: { all: 'Todos', rosto: 'Rosto', corpo: 'Corpo', pele: 'Pele' },
  procedures: {
    bioestimulador: {
      name: 'Bioestimulador de colágeno',
      desc: 'Estimula a produção natural de colágeno para mais firmeza e sustentação.',
    },
    toxina: {
      name: 'Toxina botulínica',
      desc: 'Suaviza linhas de expressão da testa e ao redor dos olhos com naturalidade.',
    },
    laser: {
      name: 'Laser de rejuvenescimento',
      desc: 'Melhora textura, poros e manchas com recuperação rápida.',
    },
    peeling: {
      name: 'Peeling químico',
      desc: 'Renovação da pele para uniformizar o tom e devolver o viço.',
    },
    criolipolise: {
      name: 'Criolipólise',
      desc: 'Redução de gordura localizada por resfriamento controlado, sem cortes.',
    },
    drenagem: {
      name: 'Drenagem linfática',
      desc: 'Reduz retenção de líquidos e inchaço com técnica manual.',
    },
  },
  from: 'a partir de',
  minutes: (n: number) => `${n} min`,
  buildPackage: 'Montar pacote',
  quizEyebrow: 'Avaliação online',
  quizTitle: 'Descubra o protocolo ideal em 3 perguntas.',
  quizStep: (s: number) => `Pergunta ${s} de 3`,
  quiz: [
    {
      q: 'Qual é o seu principal objetivo?',
      options: [
        { v: 'rejuvenescer', l: 'Suavizar linhas e rugas' },
        { v: 'firmeza', l: 'Mais firmeza e contorno' },
        { v: 'manchas', l: 'Uniformizar manchas e textura' },
        { v: 'medidas', l: 'Reduzir medidas' },
      ],
    },
    {
      q: 'Qual área você quer tratar?',
      options: [
        { v: 'rosto', l: 'Rosto' },
        { v: 'corpo', l: 'Corpo' },
        { v: 'ambos', l: 'Rosto e corpo' },
      ],
    },
    {
      q: 'Já fez algum procedimento estético?',
      options: [
        { v: 'nunca', l: 'Nunca fiz' },
        { v: 'alguns', l: 'Já fiz alguns' },
        { v: 'frequente', l: 'Faço com frequência' },
      ],
    },
  ],
  quizResultEyebrow: 'Nossa sugestão',
  quizResultLead: 'Com base nas suas respostas, estes protocolos são um bom ponto de partida:',
  quizFirstTime: 'Como é sua primeira vez, começamos com uma avaliação presencial sem compromisso.',
  quizExperienced: 'Na avaliação, revisamos seu histórico para ajustar doses e intervalos.',
  quizRestart: 'Refazer',
  quizBook: 'Reservar avaliação',
  packagesEyebrow: 'Pacotes',
  packagesTitleA: 'Monte seu pacote',
  packagesTitleEm: 'e economize',
  packagesLead: 'Quanto mais sessões, maior o desconto. O valor é atualizado na hora.',
  procedureLabel: 'Protocolo',
  sessionsLabel: 'Sessões',
  off: (p: number) => `${p}% off`,
  perSession: 'Valor por sessão',
  total: 'Total do pacote',
  savings: (v: string) => `Você economiza ${v}`,
  single: 'Sessão avulsa',
  installments: (v: string) => `ou 10× de ${v} sem juros`,
  bookPackage: 'Reservar este pacote',
  bookingTitle: 'Reserve sua avaliação',
  bookingLead: 'Deixe seu contato e o melhor período. Retornamos em até 1 hora útil.',
  name: 'Nome',
  namePlaceholder: 'Seu nome completo',
  periodLabel: 'Melhor período',
  periods: { morning: 'Manhã', afternoon: 'Tarde', evening: 'Noite' },
  interest: 'Interesse',
  send: 'Enviar pedido',
  errors: { name: 'Nome é obrigatório.', phone: 'Telefone incompleto.' },
  doneTitle: (name: string) => `Pedido recebido, ${name}!`,
  doneText: 'Nossa equipe vai te chamar no WhatsApp. Este é um demo — nenhuma reserva foi feita.',
  newRequest: 'Novo pedido',
  note: 'Procedimentos realizados por profissionais habilitados. Resultados variam de pessoa para pessoa.',
  demoBy: 'Demo por MX Studio Web',
};

type IrisText = typeof pt;

const en: IrisText = {
  tagline: 'Advanced aesthetics',
  navProtocols: 'Treatments',
  navQuiz: 'Assessment',
  navPackages: 'Packages',
  book: 'Book',
  heroEyebrow: 'Ipanema · Rio de Janeiro',
  heroTitleA: 'Your skin,',
  heroTitleEm: 'at its best',
  heroTitleB: 'pace.',
  heroLead:
    'Personalized face, body and skin treatments led by board-certified dermatologists and specialized aestheticians.',
  startQuiz: 'Take the online assessment',
  seeProtocols: 'See treatments',
  heroAlt: 'Treatment room at Íris',
  heroStats: [
    { kpi: '12', label: 'signature treatments' },
    { kpi: '4.9', label: 'Google rating' },
    { kpi: '1:1', label: 'plan per patient' },
  ],
  protocolsEyebrow: 'Treatments',
  protocolsTitleA: 'Treatments designed',
  protocolsTitleEm: 'for every area',
  areas: { all: 'All', rosto: 'Face', corpo: 'Body', pele: 'Skin' },
  procedures: {
    bioestimulador: {
      name: 'Collagen biostimulator',
      desc: 'Boosts natural collagen production for firmer, lifted skin.',
    },
    toxina: {
      name: 'Botulinum toxin',
      desc: 'Softens expression lines on the forehead and around the eyes, naturally.',
    },
    laser: {
      name: 'Rejuvenation laser',
      desc: 'Improves texture, pores and dark spots with quick recovery.',
    },
    peeling: {
      name: 'Chemical peel',
      desc: 'Skin renewal that evens out tone and brings back radiance.',
    },
    criolipolise: {
      name: 'Cryolipolysis',
      desc: 'Reduces localized fat through controlled cooling, no incisions.',
    },
    drenagem: {
      name: 'Lymphatic drainage',
      desc: 'Reduces fluid retention and swelling with a manual technique.',
    },
  },
  from: 'from',
  minutes: (n) => `${n} min`,
  buildPackage: 'Build a package',
  quizEyebrow: 'Online assessment',
  quizTitle: 'Find your ideal treatment in 3 questions.',
  quizStep: (s) => `Question ${s} of 3`,
  quiz: [
    {
      q: 'What is your main goal?',
      options: [
        { v: 'rejuvenescer', l: 'Soften lines and wrinkles' },
        { v: 'firmeza', l: 'More firmness and contour' },
        { v: 'manchas', l: 'Even out spots and texture' },
        { v: 'medidas', l: 'Reduce measurements' },
      ],
    },
    {
      q: 'Which area do you want to treat?',
      options: [
        { v: 'rosto', l: 'Face' },
        { v: 'corpo', l: 'Body' },
        { v: 'ambos', l: 'Face and body' },
      ],
    },
    {
      q: 'Have you had any aesthetic treatments before?',
      options: [
        { v: 'nunca', l: 'Never' },
        { v: 'alguns', l: 'A few' },
        { v: 'frequente', l: 'Regularly' },
      ],
    },
  ],
  quizResultEyebrow: 'Our suggestion',
  quizResultLead: 'Based on your answers, these treatments are a good starting point:',
  quizFirstTime: "Since it's your first time, we start with a no-commitment in-person assessment.",
  quizExperienced: 'During the assessment, we review your history to fine-tune doses and intervals.',
  quizRestart: 'Start over',
  quizBook: 'Book an assessment',
  packagesEyebrow: 'Packages',
  packagesTitleA: 'Build your package',
  packagesTitleEm: 'and save',
  packagesLead: 'The more sessions, the bigger the discount. The price updates instantly.',
  procedureLabel: 'Treatment',
  sessionsLabel: 'Sessions',
  off: (p) => `${p}% off`,
  perSession: 'Price per session',
  total: 'Package total',
  savings: (v) => `You save ${v}`,
  single: 'Single session',
  installments: (v) => `or 10 interest-free payments of ${v}`,
  bookPackage: 'Book this package',
  bookingTitle: 'Book your assessment',
  bookingLead: 'Leave your contact and preferred time. We reply within 1 business hour.',
  name: 'Name',
  namePlaceholder: 'Your full name',
  periodLabel: 'Preferred time',
  periods: { morning: 'Morning', afternoon: 'Afternoon', evening: 'Evening' },
  interest: 'Interested in',
  send: 'Send request',
  errors: { name: 'Name is required.', phone: 'Incomplete phone number.' },
  doneTitle: (name) => `Request received, ${name}!`,
  doneText: "Our team will message you on WhatsApp. This is a demo — no booking was made.",
  newRequest: 'New request',
  note: 'Treatments performed by licensed professionals. Results vary from person to person.',
  demoBy: 'Demo by MX Studio Web',
};

const es: IrisText = {
  tagline: 'Estética avanzada',
  navProtocols: 'Protocolos',
  navQuiz: 'Evaluación',
  navPackages: 'Paquetes',
  book: 'Reservar',
  heroEyebrow: 'Ipanema · Río de Janeiro',
  heroTitleA: 'Tu piel,',
  heroTitleEm: 'a su mejor',
  heroTitleB: 'ritmo.',
  heroLead:
    'Protocolos personalizados de rostro, cuerpo y piel, dirigidos por dermatólogas y biomédicas especializadas.',
  startQuiz: 'Hacer la evaluación online',
  seeProtocols: 'Ver protocolos',
  heroAlt: 'Sala de tratamientos de Íris',
  heroStats: [
    { kpi: '12', label: 'protocolos exclusivos' },
    { kpi: '4.9', label: 'valoración en Google' },
    { kpi: '1:1', label: 'plan por paciente' },
  ],
  protocolsEyebrow: 'Protocolos',
  protocolsTitleA: 'Tratamientos pensados',
  protocolsTitleEm: 'para cada zona',
  areas: { all: 'Todos', rosto: 'Rostro', corpo: 'Cuerpo', pele: 'Piel' },
  procedures: {
    bioestimulador: {
      name: 'Bioestimulador de colágeno',
      desc: 'Estimula la producción natural de colágeno para más firmeza y sostén.',
    },
    toxina: {
      name: 'Toxina botulínica',
      desc: 'Suaviza las líneas de expresión de la frente y alrededor de los ojos con naturalidad.',
    },
    laser: {
      name: 'Láser rejuvenecedor',
      desc: 'Mejora textura, poros y manchas con una recuperación rápida.',
    },
    peeling: {
      name: 'Peeling químico',
      desc: 'Renovación de la piel para unificar el tono y devolver la luminosidad.',
    },
    criolipolise: {
      name: 'Criolipólisis',
      desc: 'Reducción de grasa localizada por enfriamiento controlado, sin cortes.',
    },
    drenagem: {
      name: 'Drenaje linfático',
      desc: 'Reduce la retención de líquidos y la hinchazón con técnica manual.',
    },
  },
  from: 'desde',
  minutes: (n) => `${n} min`,
  buildPackage: 'Armar paquete',
  quizEyebrow: 'Evaluación online',
  quizTitle: 'Descubre el protocolo ideal en 3 preguntas.',
  quizStep: (s) => `Pregunta ${s} de 3`,
  quiz: [
    {
      q: '¿Cuál es tu objetivo principal?',
      options: [
        { v: 'rejuvenescer', l: 'Suavizar líneas y arrugas' },
        { v: 'firmeza', l: 'Más firmeza y contorno' },
        { v: 'manchas', l: 'Unificar manchas y textura' },
        { v: 'medidas', l: 'Reducir medidas' },
      ],
    },
    {
      q: '¿Qué zona quieres tratar?',
      options: [
        { v: 'rosto', l: 'Rostro' },
        { v: 'corpo', l: 'Cuerpo' },
        { v: 'ambos', l: 'Rostro y cuerpo' },
      ],
    },
    {
      q: '¿Te has hecho algún tratamiento estético?',
      options: [
        { v: 'nunca', l: 'Nunca' },
        { v: 'alguns', l: 'Algunos' },
        { v: 'frequente', l: 'Con frecuencia' },
      ],
    },
  ],
  quizResultEyebrow: 'Nuestra sugerencia',
  quizResultLead: 'Según tus respuestas, estos protocolos son un buen punto de partida:',
  quizFirstTime: 'Como es tu primera vez, empezamos con una evaluación presencial sin compromiso.',
  quizExperienced: 'En la evaluación revisamos tu historial para ajustar dosis e intervalos.',
  quizRestart: 'Repetir',
  quizBook: 'Reservar evaluación',
  packagesEyebrow: 'Paquetes',
  packagesTitleA: 'Arma tu paquete',
  packagesTitleEm: 'y ahorra',
  packagesLead: 'Cuantas más sesiones, mayor el descuento. El precio se actualiza al instante.',
  procedureLabel: 'Protocolo',
  sessionsLabel: 'Sesiones',
  off: (p) => `${p}% de descuento`,
  perSession: 'Precio por sesión',
  total: 'Total del paquete',
  savings: (v) => `Ahorras ${v}`,
  single: 'Sesión suelta',
  installments: (v) => `o 10 cuotas de ${v} sin interés`,
  bookPackage: 'Reservar este paquete',
  bookingTitle: 'Reserva tu evaluación',
  bookingLead: 'Déjanos tu contacto y la franja que prefieras. Respondemos en menos de 1 hora hábil.',
  name: 'Nombre',
  namePlaceholder: 'Tu nombre completo',
  periodLabel: 'Mejor franja',
  periods: { morning: 'Mañana', afternoon: 'Tarde', evening: 'Noche' },
  interest: 'Interés',
  send: 'Enviar solicitud',
  errors: { name: 'El nombre es obligatorio.', phone: 'Teléfono incompleto.' },
  doneTitle: (name) => `¡Solicitud recibida, ${name}!`,
  doneText: 'Nuestro equipo te escribirá por WhatsApp. Esto es una demo: no se hizo ninguna reserva.',
  newRequest: 'Nueva solicitud',
  note: 'Tratamientos realizados por profesionales habilitados. Los resultados varían de una persona a otra.',
  demoBy: 'Demo por MX Studio Web',
};

export const content: Record<Locale, IrisText> = { pt, en, es };
