import type { Locale } from '@/i18n/config';

const pt = {
  method: 'Método Larissa Nogueira',
  navProgram: 'Programa',
  navStudents: 'Alunos',
  navPlans: 'Planos',
  navFaq: 'FAQ',
  start: 'Quero começar',
  seats: (n: number) => `Nova turma · restam ${n} vagas`,
  heroTitleA: 'Do',
  heroTitleEm: 'nevoeiro',
  heroTitleB: 'para uma rota clara.',
  heroLead:
    'Um método de 8 semanas pra você sair da paralisia analítica e tomar decisões de carreira e vida com clareza — mesmo em momento de virada.',
  offerEnds: 'Oferta termina em',
  seePlans: 'Ver os planos',
  freeClass: 'Assistir aula grátis',
  rating: '4.9 · 1.482 alunos formados',
  programEyebrow: 'O programa',
  programTitleA: '8 módulos, 8 semanas,',
  programTitleEm: 'uma virada',
  modules: [
    { title: 'Mentalidade e ponto de partida', duration: '58min · 6 aulas' },
    { title: 'Diagnóstico da rota atual', duration: '1h12 · 8 aulas' },
    { title: 'Escolha e priorização', duration: '48min · 5 aulas' },
    { title: 'Ferramentas do método', duration: '2h30 · 12 aulas' },
    { title: 'Execução em ciclos curtos', duration: '1h48 · 9 aulas' },
    { title: 'Rotina e sustentação', duration: '52min · 6 aulas' },
    { title: 'Curvas, imprevistos e recomeços', duration: '1h05 · 7 aulas' },
    { title: 'A próxima rota', duration: '38min · 4 aulas' },
  ],
  studentsEyebrow: 'Alunos',
  studentsTitle: 'Gente igual você que virou de rota.',
  testimonials: [
    {
      role: 'Trocou de área aos 38',
      text: 'Consegui sair de uma carreira que não me servia mais sem me sentir irresponsável. O método deu clareza pra decisões que eu adiava há anos.',
    },
    {
      role: 'Empreendedor',
      text: 'Já tinha feito outros cursos, mas esse é o mais prático. As ferramentas do módulo 4 mudaram como eu tomo decisões.',
    },
    {
      role: 'Voltou aos estudos',
      text: 'A parte de mentalidade me deu coragem pra recomeçar. Estou fazendo minha primeira pós agora, aos 42.',
    },
  ],
  teacherEyebrow: 'Quem ensina',
  teacherTitleA: 'Larissa Nogueira,',
  teacherTitleEm: 'mentora',
  teacherTitleB: 'de virada de carreira.',
  teacherBio:
    'Psicóloga, coach ICF e mentora há mais de 12 anos. Mais de 1.400 pessoas passaram pelo método Rota Clara — profissionais de todas as áreas que precisavam sair do lugar-comum e recomeçar com clareza.',
  teacherStats: [
    { kpi: '12+ anos', label: 'de mentoria' },
    { kpi: '1.482', label: 'alunos formados' },
    { kpi: 'ICF', label: 'certificação' },
  ],
  plansEyebrow: 'Investimento',
  plansTitleA: 'Escolha o seu',
  plansTitleEm: 'nível',
  plansLead: 'Todos os planos incluem 15 dias de garantia incondicional.',
  plans: {
    solo: {
      name: 'Solo',
      features: [
        'Acesso ao curso principal (8 módulos)',
        '12 meses de acesso',
        'Certificado ao final',
        'Comunidade no Telegram',
      ],
    },
    plus: {
      name: 'Método completo',
      features: [
        'Tudo do Solo',
        '4 encontros ao vivo com a Larissa',
        'Vitalício + atualizações',
        'Grupo VIP com feedback',
        'Bônus: kit de planilhas',
      ],
    },
    pro: {
      name: 'Mentoria 1:1',
      features: [
        'Tudo do completo',
        '3 mentorias 1:1 com a Larissa',
        'Revisão do seu projeto',
        'WhatsApp direto por 90 dias',
      ],
    },
  },
  mostChosen: 'Mais escolhido',
  installmentsOf: (n: number) => `${n}× de`,
  pixPrice: (value: string) => `ou ${value} à vista no PIX (−5%)`,
  chosen: '✓ Escolhido',
  choose: 'Escolher plano',
  goCheckout: (plan: string) => `Ir pro checkout · ${plan}`,
  secure: 'Ambiente seguro · SSL 256 bits · Garantia de 15 dias',
  faqEyebrow: 'FAQ',
  faqTitle: 'Dúvidas frequentes',
  faq: [
    {
      q: 'Pra quem é o Método Rota Clara?',
      a: 'Pra quem está numa transição de vida ou carreira e quer sair da paralisia analítica. Serve pra quem quer trocar de área, começar um negócio, retomar estudos ou reorganizar o dia a dia.',
    },
    {
      q: 'Vou precisar de conhecimento prévio?',
      a: 'Não. O método é feito pra ser prático desde o primeiro módulo. Você começa aplicando na primeira aula.',
    },
    {
      q: 'E se eu não gostar?',
      a: 'Garantia incondicional de 15 dias. Se não fizer sentido, devolvo 100% do valor. Sem enrolação.',
    },
    {
      q: 'Como funciona o pagamento?',
      a: 'À vista no PIX (5% OFF) ou parcelado em até 12× sem juros no cartão. O acesso libera na hora.',
    },
    {
      q: 'Quanto tempo por semana preciso dedicar?',
      a: 'De 2 a 4 horas. As aulas ficam em blocos de 8 a 20 minutos, fáceis de encaixar entre compromissos.',
    },
  ],
  close: 'Fechar',
  secureCheckout: 'Checkout seguro',
  buying: 'Você está comprando',
  step1: '1 · Seus dados',
  fullName: 'Nome completo',
  emailPlaceholder: 'voce@dominio.com',
  payment: 'Pagamento',
  pix: 'PIX',
  card: 'Cartão',
  pixDesc: '5% OFF · aprovação em segundos',
  cardDesc: (n: number) => `${n}× sem juros`,
  continue: 'Continuar',
  step2Pix: '2 · Confirmação',
  step2Card: '2 · Cartão',
  cardNumber: 'Número do cartão',
  cardName: 'Nome como está no cartão',
  expiry: 'MM/AA',
  pixInfo:
    'Ao confirmar, geramos o QR Code PIX pra pagamento. O acesso libera automaticamente após a confirmação bancária (poucos segundos).',
  total: 'Total',
  youSave: (value: string) => `Você economiza ${value}`,
  back: 'Voltar',
  finish: 'Finalizar',
  welcome: (name: string) => `Bem-vindo à Rota Clara, ${name}!`,
  accessSent: (email: string) =>
    `Seu acesso foi liberado no e-mail ${email}. Este é um demo — nenhum pagamento processado.`,
  backToPage: 'Voltar à página',
  errors: {
    name: 'Nome obrigatório.',
    email: 'E-mail inválido.',
    payment: 'Escolha a forma de pagamento.',
    number: 'Cartão inválido.',
    cardName: 'Nome no cartão obrigatório.',
    expiry: 'Formato MM/AA.',
    cvv: 'CVV inválido.',
  },
  demoBy: 'Demo por MX Studio Web',
};

type RotaClaraText = typeof pt;

const en: RotaClaraText = {
  method: 'The Larissa Nogueira Method',
  navProgram: 'Program',
  navStudents: 'Students',
  navPlans: 'Plans',
  navFaq: 'FAQ',
  start: 'I want to start',
  seats: (n) => `New cohort · ${n} spots left`,
  heroTitleA: 'From',
  heroTitleEm: 'fog',
  heroTitleB: 'to a clear route.',
  heroLead:
    'An 8-week method to break out of analysis paralysis and make career and life decisions with clarity — even in the middle of a big shift.',
  offerEnds: 'Offer ends in',
  seePlans: 'See the plans',
  freeClass: 'Watch a free class',
  rating: '4.9 · 1,482 graduates',
  programEyebrow: 'The program',
  programTitleA: '8 modules, 8 weeks,',
  programTitleEm: 'one turning point',
  modules: [
    { title: 'Mindset and starting point', duration: '58min · 6 lessons' },
    { title: 'Diagnosing your current route', duration: '1h12 · 8 lessons' },
    { title: 'Choosing and prioritizing', duration: '48min · 5 lessons' },
    { title: 'Tools of the method', duration: '2h30 · 12 lessons' },
    { title: 'Execution in short cycles', duration: '1h48 · 9 lessons' },
    { title: 'Routine and staying on track', duration: '52min · 6 lessons' },
    { title: 'Detours, setbacks and fresh starts', duration: '1h05 · 7 lessons' },
    { title: 'The next route', duration: '38min · 4 lessons' },
  ],
  studentsEyebrow: 'Students',
  studentsTitle: 'People just like you who changed course.',
  testimonials: [
    {
      role: 'Changed careers at 38',
      text: "I managed to leave a career that no longer fit me without feeling irresponsible. The method gave me clarity on decisions I'd been putting off for years.",
    },
    {
      role: 'Entrepreneur',
      text: "I'd taken other courses, but this is the most practical one. The tools in module 4 changed how I make decisions.",
    },
    {
      role: 'Went back to school',
      text: "The mindset part gave me the courage to start over. I'm doing my first graduate program now, at 42.",
    },
  ],
  teacherEyebrow: 'Your teacher',
  teacherTitleA: 'Larissa Nogueira,',
  teacherTitleEm: 'mentor',
  teacherTitleB: 'for career changes.',
  teacherBio:
    'Psychologist, ICF coach and mentor for over 12 years. More than 1,400 people have gone through the Rota Clara method — professionals from every field who needed to break out of the rut and start over with clarity.',
  teacherStats: [
    { kpi: '12+ years', label: 'of mentoring' },
    { kpi: '1,482', label: 'graduates' },
    { kpi: 'ICF', label: 'certified' },
  ],
  plansEyebrow: 'Investment',
  plansTitleA: 'Choose your',
  plansTitleEm: 'level',
  plansLead: 'Every plan includes an unconditional 15-day guarantee.',
  plans: {
    solo: {
      name: 'Solo',
      features: [
        'Access to the main course (8 modules)',
        '12 months of access',
        'Certificate of completion',
        'Telegram community',
      ],
    },
    plus: {
      name: 'Complete method',
      features: [
        'Everything in Solo',
        '4 live sessions with Larissa',
        'Lifetime access + updates',
        'VIP group with feedback',
        'Bonus: spreadsheet kit',
      ],
    },
    pro: {
      name: '1:1 Mentoring',
      features: [
        'Everything in Complete',
        '3 one-on-one sessions with Larissa',
        'Review of your project',
        'Direct WhatsApp access for 90 days',
      ],
    },
  },
  mostChosen: 'Most popular',
  installmentsOf: (n) => `${n} payments of`,
  pixPrice: (value) => `or ${value} upfront with PIX (−5%)`,
  chosen: '✓ Selected',
  choose: 'Choose plan',
  goCheckout: (plan) => `Go to checkout · ${plan}`,
  secure: 'Secure checkout · 256-bit SSL · 15-day guarantee',
  faqEyebrow: 'FAQ',
  faqTitle: 'Frequently asked questions',
  faq: [
    {
      q: 'Who is the Rota Clara Method for?',
      a: 'For anyone going through a life or career transition who wants to escape analysis paralysis. It works if you want to switch fields, start a business, go back to school or reorganize your daily life.',
    },
    {
      q: 'Do I need any prior knowledge?',
      a: 'No. The method is practical from the very first module — you start applying it in lesson one.',
    },
    {
      q: "What if I don't like it?",
      a: "Unconditional 15-day guarantee. If it doesn't click, I'll refund 100% of what you paid. No hassle.",
    },
    {
      q: 'How does payment work?',
      a: 'Pay upfront with PIX (5% off) or in up to 12 interest-free card installments. Access is unlocked right away.',
    },
    {
      q: 'How much time per week do I need?',
      a: '2 to 4 hours. Lessons come in 8- to 20-minute blocks that are easy to fit between commitments.',
    },
  ],
  close: 'Close',
  secureCheckout: 'Secure checkout',
  buying: "You're buying",
  step1: '1 · Your details',
  fullName: 'Full name',
  emailPlaceholder: 'you@domain.com',
  payment: 'Payment',
  pix: 'PIX',
  card: 'Card',
  pixDesc: '5% off · approved in seconds',
  cardDesc: (n) => `${n} interest-free payments`,
  continue: 'Continue',
  step2Pix: '2 · Confirmation',
  step2Card: '2 · Card',
  cardNumber: 'Card number',
  cardName: 'Name on card',
  expiry: 'MM/YY',
  pixInfo:
    "When you confirm, we'll generate a PIX QR code for payment. Access is unlocked automatically once the bank confirms (a few seconds).",
  total: 'Total',
  youSave: (value) => `You save ${value}`,
  back: 'Back',
  finish: 'Complete purchase',
  welcome: (name) => `Welcome to Rota Clara, ${name}!`,
  accessSent: (email) => `Your access was sent to ${email}. This is a demo — no payment was processed.`,
  backToPage: 'Back to the page',
  errors: {
    name: 'Name is required.',
    email: 'Invalid email.',
    payment: 'Choose a payment method.',
    number: 'Invalid card.',
    cardName: 'Name on card is required.',
    expiry: 'Use the MM/YY format.',
    cvv: 'Invalid CVV.',
  },
  demoBy: 'Demo by MX Studio Web',
};

const es: RotaClaraText = {
  method: 'Método Larissa Nogueira',
  navProgram: 'Programa',
  navStudents: 'Alumnos',
  navPlans: 'Planes',
  navFaq: 'FAQ',
  start: 'Quiero empezar',
  seats: (n) => `Nuevo grupo · quedan ${n} plazas`,
  heroTitleA: 'De la',
  heroTitleEm: 'niebla',
  heroTitleB: 'a una ruta clara.',
  heroLead:
    'Un método de 8 semanas para salir de la parálisis por análisis y tomar decisiones de carrera y de vida con claridad, incluso en pleno cambio.',
  offerEnds: 'La oferta termina en',
  seePlans: 'Ver los planes',
  freeClass: 'Ver clase gratis',
  rating: '4.9 · 1.482 alumnos graduados',
  programEyebrow: 'El programa',
  programTitleA: '8 módulos, 8 semanas,',
  programTitleEm: 'un giro',
  modules: [
    { title: 'Mentalidad y punto de partida', duration: '58min · 6 clases' },
    { title: 'Diagnóstico de tu ruta actual', duration: '1h12 · 8 clases' },
    { title: 'Elección y priorización', duration: '48min · 5 clases' },
    { title: 'Herramientas del método', duration: '2h30 · 12 clases' },
    { title: 'Ejecución en ciclos cortos', duration: '1h48 · 9 clases' },
    { title: 'Rutina y constancia', duration: '52min · 6 clases' },
    { title: 'Curvas, imprevistos y nuevos comienzos', duration: '1h05 · 7 clases' },
    { title: 'La próxima ruta', duration: '38min · 4 clases' },
  ],
  studentsEyebrow: 'Alumnos',
  studentsTitle: 'Gente como tú que cambió de rumbo.',
  testimonials: [
    {
      role: 'Cambió de área a los 38',
      text: 'Logré dejar una carrera que ya no me servía sin sentirme irresponsable. El método me dio claridad para decisiones que llevaba años posponiendo.',
    },
    {
      role: 'Emprendedor',
      text: 'Ya había hecho otros cursos, pero este es el más práctico. Las herramientas del módulo 4 cambiaron cómo tomo decisiones.',
    },
    {
      role: 'Volvió a estudiar',
      text: 'La parte de mentalidad me dio valor para empezar de nuevo. Estoy haciendo mi primer posgrado ahora, a los 42.',
    },
  ],
  teacherEyebrow: 'Quién enseña',
  teacherTitleA: 'Larissa Nogueira,',
  teacherTitleEm: 'mentora',
  teacherTitleB: 'de cambio de carrera.',
  teacherBio:
    'Psicóloga, coach ICF y mentora desde hace más de 12 años. Más de 1.400 personas han pasado por el método Rota Clara: profesionales de todas las áreas que necesitaban salir de la rutina y empezar de nuevo con claridad.',
  teacherStats: [
    { kpi: '12+ años', label: 'de mentoría' },
    { kpi: '1.482', label: 'alumnos graduados' },
    { kpi: 'ICF', label: 'certificación' },
  ],
  plansEyebrow: 'Inversión',
  plansTitleA: 'Elige tu',
  plansTitleEm: 'nivel',
  plansLead: 'Todos los planes incluyen 15 días de garantía incondicional.',
  plans: {
    solo: {
      name: 'Solo',
      features: [
        'Acceso al curso principal (8 módulos)',
        '12 meses de acceso',
        'Certificado al finalizar',
        'Comunidad en Telegram',
      ],
    },
    plus: {
      name: 'Método completo',
      features: [
        'Todo lo de Solo',
        '4 encuentros en vivo con Larissa',
        'Acceso de por vida + actualizaciones',
        'Grupo VIP con feedback',
        'Bonus: kit de hojas de cálculo',
      ],
    },
    pro: {
      name: 'Mentoría 1:1',
      features: [
        'Todo lo del Completo',
        '3 mentorías 1:1 con Larissa',
        'Revisión de tu proyecto',
        'WhatsApp directo durante 90 días',
      ],
    },
  },
  mostChosen: 'El más elegido',
  installmentsOf: (n) => `${n}× de`,
  pixPrice: (value) => `o ${value} al contado con PIX (−5%)`,
  chosen: '✓ Elegido',
  choose: 'Elegir plan',
  goCheckout: (plan) => `Ir al pago · ${plan}`,
  secure: 'Entorno seguro · SSL de 256 bits · Garantía de 15 días',
  faqEyebrow: 'FAQ',
  faqTitle: 'Preguntas frecuentes',
  faq: [
    {
      q: '¿Para quién es el Método Rota Clara?',
      a: 'Para quien está en una transición de vida o de carrera y quiere salir de la parálisis por análisis. Sirve si quieres cambiar de área, emprender, retomar los estudios o reorganizar tu día a día.',
    },
    {
      q: '¿Necesito conocimientos previos?',
      a: 'No. El método es práctico desde el primer módulo: empiezas a aplicarlo en la primera clase.',
    },
    {
      q: '¿Y si no me gusta?',
      a: 'Garantía incondicional de 15 días. Si no te encaja, te devuelvo el 100% del importe. Sin complicaciones.',
    },
    {
      q: '¿Cómo funciona el pago?',
      a: 'Al contado con PIX (5% de descuento) o hasta en 12 cuotas sin interés con tarjeta. El acceso se libera al instante.',
    },
    {
      q: '¿Cuánto tiempo a la semana necesito?',
      a: 'De 2 a 4 horas. Las clases van en bloques de 8 a 20 minutos, fáciles de encajar entre compromisos.',
    },
  ],
  close: 'Cerrar',
  secureCheckout: 'Pago seguro',
  buying: 'Estás comprando',
  step1: '1 · Tus datos',
  fullName: 'Nombre completo',
  emailPlaceholder: 'tu@dominio.com',
  payment: 'Pago',
  pix: 'PIX',
  card: 'Tarjeta',
  pixDesc: '5% de descuento · aprobación en segundos',
  cardDesc: (n) => `${n} cuotas sin interés`,
  continue: 'Continuar',
  step2Pix: '2 · Confirmación',
  step2Card: '2 · Tarjeta',
  cardNumber: 'Número de tarjeta',
  cardName: 'Nombre tal como aparece en la tarjeta',
  expiry: 'MM/AA',
  pixInfo:
    'Al confirmar, generamos el código QR de PIX para el pago. El acceso se libera automáticamente tras la confirmación bancaria (unos segundos).',
  total: 'Total',
  youSave: (value) => `Ahorras ${value}`,
  back: 'Volver',
  finish: 'Finalizar',
  welcome: (name) => `¡Bienvenido a Rota Clara, ${name}!`,
  accessSent: (email) => `Tu acceso se envió a ${email}. Esto es una demo: no se procesó ningún pago.`,
  backToPage: 'Volver a la página',
  errors: {
    name: 'Nombre obligatorio.',
    email: 'Correo no válido.',
    payment: 'Elige la forma de pago.',
    number: 'Tarjeta no válida.',
    cardName: 'El nombre de la tarjeta es obligatorio.',
    expiry: 'Formato MM/AA.',
    cvv: 'CVV no válido.',
  },
  demoBy: 'Demo por MX Studio Web',
};

export const content: Record<Locale, RotaClaraText> = { pt, en, es };
