import type { Locale } from '@/i18n/config';

const pt = {
  tagline: 'Salão & beleza',
  navServices: 'Serviços',
  navTeam: 'Equipe',
  navBook: 'Agendar',
  heroEyebrow: 'Leblon · Rio de Janeiro',
  heroTitleA: 'Cabelo, unhas e make',
  heroTitleEm: 'com hora marcada',
  heroLead:
    'Escolha os serviços, a profissional e o horário em menos de um minuto. A confirmação chega no seu WhatsApp.',
  book: 'Agendar horário',
  seeServices: 'Ver serviços',
  heroAlt: 'Ambiente do Maré Salão',
  heroStats: [
    { kpi: '4.9', label: 'avaliação no Google' },
    { kpi: '4', label: 'especialidades' },
    { kpi: '1 min', label: 'para agendar' },
  ],
  servicesEyebrow: 'Serviços',
  servicesTitleA: 'Monte o seu horário',
  servicesTitleEm: 'serviço por serviço',
  servicesLead: 'Toque em adicionar e o preço e a duração somam na hora.',
  cats: { cabelo: 'Cabelo', unhas: 'Unhas', make: 'Maquiagem', sobrancelhas: 'Sobrancelhas' },
  services: {
    corte: { name: 'Corte feminino', desc: 'Lavagem, corte e finalização' },
    escova: { name: 'Escova modelada', desc: 'Escova com acabamento e brilho' },
    coloracao: { name: 'Coloração', desc: 'Cor global com produtos sem amônia' },
    mechas: { name: 'Mechas e luzes', desc: 'Iluminado sob medida, com tonalização' },
    hidratacao: { name: 'Hidratação profunda', desc: 'Tratamento para fios secos e opacos' },
    manicure: { name: 'Manicure', desc: 'Cutilagem e esmaltação' },
    pedicure: { name: 'Pedicure', desc: 'Cutilagem, lixa e esmaltação' },
    gel: { name: 'Unha em gel', desc: 'Alongamento com acabamento natural' },
    social: { name: 'Maquiagem social', desc: 'Para festas e eventos, com cílios' },
    noiva: { name: 'Maquiagem de noiva', desc: 'Teste prévio + dia da cerimônia' },
    design: { name: 'Design de sobrancelhas', desc: 'Mapeamento, pinça ou linha' },
    henna: { name: 'Design com henna', desc: 'Preenchimento temporário dos fios' },
  },
  minutes: (n: number) => (n >= 60 ? `${Math.floor(n / 60)}h${n % 60 ? ` ${n % 60}min` : ''}` : `${n} min`),
  add: 'Adicionar',
  added: 'Adicionado',
  teamEyebrow: 'Equipe',
  teamTitleA: 'Quem cuida',
  teamTitleEm: 'de você',
  roles: {
    camila: 'Cabeleireira e colorista',
    bianca: 'Nail designer',
    juliana: 'Maquiadora',
    rafaela: 'Cabeleireira e designer de sobrancelhas',
  },
  bookEyebrow: 'Agendamento',
  bookTitle: 'Escolha o seu horário',
  step: (n: number) => `Passo ${n}`,
  pickedTitle: 'Serviços escolhidos',
  pickedEmpty: 'Nenhum serviço ainda. Adicione na lista acima.',
  remove: 'Remover',
  proTitle: 'Profissional',
  anyPro: 'Sem preferência',
  anyProNote: 'A primeira profissional livre na especialidade.',
  noSinglePro: 'Nenhuma profissional faz todos esses serviços: dividimos entre a equipe.',
  dayTitle: 'Dia',
  closed: 'Fechado',
  timeTitle: 'Horário',
  timeHint: 'Horários em cinza já estão ocupados.',
  pickDayFirst: 'Escolha um dia para ver os horários.',
  contactTitle: 'Seus dados',
  name: 'Nome',
  namePlaceholder: 'Como podemos te chamar?',
  total: 'Total',
  duration: 'Duração',
  confirm: 'Confirmar agendamento',
  errors: {
    services: 'Adicione pelo menos um serviço.',
    time: 'Escolha dia e horário.',
    name: 'Nome é obrigatório.',
    phone: 'Telefone incompleto.',
  },
  doneTitle: (name: string) => `Horário reservado, ${name}!`,
  doneText: 'A confirmação chegaria no seu WhatsApp. Este é um demo — nenhum horário foi reservado.',
  newBooking: 'Novo agendamento',
  bar: (n: number) => (n === 1 ? '1 serviço' : `${n} serviços`),
  infoAddress: 'Rua Dias Ferreira · Leblon',
  infoHours: 'Ter a sáb, 9h às 20h',
  note: 'Preços a partir de, conforme comprimento e volume do cabelo.',
  demoBy: 'Demo por MX Studio Web',
};

type MareText = typeof pt;

const en: MareText = {
  tagline: 'Salon & beauty',
  navServices: 'Services',
  navTeam: 'Team',
  navBook: 'Book',
  heroEyebrow: 'Leblon · Rio de Janeiro',
  heroTitleA: 'Hair, nails and make-up',
  heroTitleEm: 'by appointment',
  heroLead:
    'Pick your services, your stylist and a time in under a minute. The confirmation lands on your WhatsApp.',
  book: 'Book a time',
  seeServices: 'See services',
  heroAlt: 'Inside Maré Salão',
  heroStats: [
    { kpi: '4.9', label: 'Google rating' },
    { kpi: '4', label: 'specialties' },
    { kpi: '1 min', label: 'to book' },
  ],
  servicesEyebrow: 'Services',
  servicesTitleA: 'Build your appointment',
  servicesTitleEm: 'one service at a time',
  servicesLead: 'Tap add and the price and duration add up instantly.',
  cats: { cabelo: 'Hair', unhas: 'Nails', make: 'Make-up', sobrancelhas: 'Brows' },
  services: {
    corte: { name: "Women's haircut", desc: 'Wash, cut and finish' },
    escova: { name: 'Blow-dry', desc: 'Styled blow-dry with shine' },
    coloracao: { name: 'Colour', desc: 'All-over colour, ammonia-free' },
    mechas: { name: 'Highlights', desc: 'Tailored highlights with toner' },
    hidratacao: { name: 'Deep conditioning', desc: 'Treatment for dry, dull hair' },
    manicure: { name: 'Manicure', desc: 'Cuticle care and polish' },
    pedicure: { name: 'Pedicure', desc: 'Cuticle care, filing and polish' },
    gel: { name: 'Gel nails', desc: 'Extensions with a natural finish' },
    social: { name: 'Event make-up', desc: 'For parties and events, lashes included' },
    noiva: { name: 'Bridal make-up', desc: 'Trial + wedding day' },
    design: { name: 'Brow shaping', desc: 'Mapping, tweezers or thread' },
    henna: { name: 'Henna brows', desc: 'Temporary fill for sparse brows' },
  },
  minutes: (n) => (n >= 60 ? `${Math.floor(n / 60)}h${n % 60 ? ` ${n % 60}min` : ''}` : `${n} min`),
  add: 'Add',
  added: 'Added',
  teamEyebrow: 'Team',
  teamTitleA: 'The people',
  teamTitleEm: 'looking after you',
  roles: {
    camila: 'Stylist and colourist',
    bianca: 'Nail designer',
    juliana: 'Make-up artist',
    rafaela: 'Stylist and brow designer',
  },
  bookEyebrow: 'Booking',
  bookTitle: 'Pick your time',
  step: (n) => `Step ${n}`,
  pickedTitle: 'Your services',
  pickedEmpty: 'No services yet. Add them from the list above.',
  remove: 'Remove',
  proTitle: 'Professional',
  anyPro: 'No preference',
  anyProNote: 'The first free professional in that specialty.',
  noSinglePro: 'No single professional does all of these: we split them across the team.',
  dayTitle: 'Day',
  closed: 'Closed',
  timeTitle: 'Time',
  timeHint: 'Grey times are already taken.',
  pickDayFirst: 'Pick a day to see the times.',
  contactTitle: 'Your details',
  name: 'Name',
  namePlaceholder: 'What should we call you?',
  total: 'Total',
  duration: 'Duration',
  confirm: 'Confirm booking',
  errors: {
    services: 'Add at least one service.',
    time: 'Pick a day and time.',
    name: 'Name is required.',
    phone: 'Incomplete phone number.',
  },
  doneTitle: (name) => `You're booked, ${name}!`,
  doneText: 'The confirmation would go to your WhatsApp. This is a demo — no appointment was made.',
  newBooking: 'New booking',
  bar: (n) => (n === 1 ? '1 service' : `${n} services`),
  infoAddress: 'Rua Dias Ferreira · Leblon',
  infoHours: 'Tue to Sat, 9am to 8pm',
  note: 'Starting prices; final price depends on hair length and volume.',
  demoBy: 'Demo by MX Studio Web',
};

const es: MareText = {
  tagline: 'Salón y belleza',
  navServices: 'Servicios',
  navTeam: 'Equipo',
  navBook: 'Reservar',
  heroEyebrow: 'Leblon · Río de Janeiro',
  heroTitleA: 'Pelo, uñas y maquillaje',
  heroTitleEm: 'con cita previa',
  heroLead:
    'Elige los servicios, la profesional y el horario en menos de un minuto. La confirmación llega a tu WhatsApp.',
  book: 'Reservar cita',
  seeServices: 'Ver servicios',
  heroAlt: 'Interior de Maré Salão',
  heroStats: [
    { kpi: '4.9', label: 'valoración en Google' },
    { kpi: '4', label: 'especialidades' },
    { kpi: '1 min', label: 'para reservar' },
  ],
  servicesEyebrow: 'Servicios',
  servicesTitleA: 'Arma tu cita',
  servicesTitleEm: 'servicio a servicio',
  servicesLead: 'Toca añadir y el precio y la duración se suman al momento.',
  cats: { cabelo: 'Pelo', unhas: 'Uñas', make: 'Maquillaje', sobrancelhas: 'Cejas' },
  services: {
    corte: { name: 'Corte de mujer', desc: 'Lavado, corte y peinado' },
    escova: { name: 'Brushing', desc: 'Secado modelado con brillo' },
    coloracao: { name: 'Coloración', desc: 'Color global sin amoníaco' },
    mechas: { name: 'Mechas y reflejos', desc: 'Iluminación a medida, con matiz' },
    hidratacao: { name: 'Hidratación profunda', desc: 'Tratamiento para pelo seco y apagado' },
    manicure: { name: 'Manicura', desc: 'Cutículas y esmaltado' },
    pedicure: { name: 'Pedicura', desc: 'Cutículas, limado y esmaltado' },
    gel: { name: 'Uñas de gel', desc: 'Extensión con acabado natural' },
    social: { name: 'Maquillaje de evento', desc: 'Para fiestas y eventos, con pestañas' },
    noiva: { name: 'Maquillaje de novia', desc: 'Prueba previa + día de la boda' },
    design: { name: 'Diseño de cejas', desc: 'Mapeo, pinza o hilo' },
    henna: { name: 'Cejas con henna', desc: 'Relleno temporal del vello' },
  },
  minutes: (n) => (n >= 60 ? `${Math.floor(n / 60)}h${n % 60 ? ` ${n % 60}min` : ''}` : `${n} min`),
  add: 'Añadir',
  added: 'Añadido',
  teamEyebrow: 'Equipo',
  teamTitleA: 'Quién',
  teamTitleEm: 'te atiende',
  roles: {
    camila: 'Peluquera y colorista',
    bianca: 'Diseñadora de uñas',
    juliana: 'Maquilladora',
    rafaela: 'Peluquera y diseñadora de cejas',
  },
  bookEyebrow: 'Reserva',
  bookTitle: 'Elige tu horario',
  step: (n) => `Paso ${n}`,
  pickedTitle: 'Servicios elegidos',
  pickedEmpty: 'Aún no hay servicios. Añádelos desde la lista de arriba.',
  remove: 'Quitar',
  proTitle: 'Profesional',
  anyPro: 'Sin preferencia',
  anyProNote: 'La primera profesional libre en esa especialidad.',
  noSinglePro: 'Ninguna profesional hace todos estos servicios: los repartimos en el equipo.',
  dayTitle: 'Día',
  closed: 'Cerrado',
  timeTitle: 'Horario',
  timeHint: 'Los horarios en gris ya están ocupados.',
  pickDayFirst: 'Elige un día para ver los horarios.',
  contactTitle: 'Tus datos',
  name: 'Nombre',
  namePlaceholder: '¿Cómo te llamamos?',
  total: 'Total',
  duration: 'Duración',
  confirm: 'Confirmar reserva',
  errors: {
    services: 'Añade al menos un servicio.',
    time: 'Elige día y horario.',
    name: 'El nombre es obligatorio.',
    phone: 'Teléfono incompleto.',
  },
  doneTitle: (name) => `¡Cita reservada, ${name}!`,
  doneText: 'La confirmación llegaría a tu WhatsApp. Esto es una demo: no se reservó ninguna cita.',
  newBooking: 'Nueva reserva',
  bar: (n) => (n === 1 ? '1 servicio' : `${n} servicios`),
  infoAddress: 'Rua Dias Ferreira · Leblon',
  infoHours: 'De martes a sábado, de 9 a 20 h',
  note: 'Precios desde; el valor final depende del largo y volumen del pelo.',
  demoBy: 'Demo por MX Studio Web',
};

export const content: Record<Locale, MareText> = { pt, en, es };
