import type { Locale } from '@/i18n/config';

const pt = {
  tagline: 'Engenharia & obras',
  navEstimate: 'Orçamento',
  navProjects: 'Obras',
  navStages: 'Etapas',
  cta: 'Pedir visita técnica',
  heroEyebrow: 'Construção e reforma · Rio de Janeiro e Niterói',
  heroTitleA: 'Construímos o que você imagina,',
  heroTitleEm: 'no prazo',
  heroTitleB: 'que prometemos.',
  heroLead:
    'Casas, reformas e obras comerciais com cronograma fechado, engenheiro responsável e relatório semanal com fotos.',
  simulate: 'Simular orçamento',
  seeProjects: 'Ver obras entregues',
  heroAlt: 'Obra da Alicerce Engenharia',
  stats: [
    { kpi: '212', label: 'obras entregues' },
    { kpi: '18', label: 'anos de mercado' },
    { kpi: '96%', label: 'entregues no prazo' },
    { kpi: '100%', label: 'com ART registrada' },
  ],
  estimateEyebrow: 'Simulador',
  estimateTitleA: 'Quanto custa a',
  estimateTitleEm: 'sua obra',
  estimateLead: 'Uma estimativa inicial em segundos. O valor final sai depois da visita técnica.',
  typeLabel: 'Tipo de obra',
  types: { casa: 'Casa nova', reforma: 'Reforma', ampliacao: 'Ampliação', comercial: 'Comercial' },
  areaLabel: 'Área construída',
  standardLabel: 'Padrão de acabamento',
  standards: { economico: 'Econômico', medio: 'Médio', alto: 'Alto padrão' },
  resultLabel: 'Estimativa',
  rangeSeparator: 'a',
  perM2: (v: string) => `≈ ${v} por m²`,
  durationLabel: 'Prazo estimado',
  months: (n: number) => `${n} ${n === 1 ? 'mês' : 'meses'}`,
  estimateNote: 'Valores de referência para a região metropolitana do Rio. Não substituem o orçamento técnico.',
  requestVisit: 'Quero uma visita técnica',
  projectsEyebrow: 'Obras entregues',
  projectsTitle: 'Um portfólio que você pode visitar.',
  categories: { all: 'Todas', residencial: 'Residencial', comercial: 'Comercial', reforma: 'Reforma' },
  projects: {
    o1: 'Residência Pedra Bonita',
    o2: 'Edifício Comercial Lapa 12',
    o3: 'Retrofit Casa Cosme Velho',
    o4: 'Casa Jardim Botânico',
    o5: 'Loja-conceito Ipanema',
    o6: 'Cobertura Icaraí',
  },
  delivered: (y: string) => `Entregue em ${y}`,
  stagesEyebrow: 'Etapas da obra',
  stagesTitleA: 'Você acompanha',
  stagesTitleEm: 'cada etapa',
  stageOf: (n: number, total: number) => `Etapa ${n} de ${total}`,
  deliverablesLabel: 'O que você recebe',
  stages: [
    {
      title: 'Projeto e aprovação',
      duration: '4–8 semanas',
      desc: 'Levantamento, projeto arquitetônico e complementares, aprovação na prefeitura e cronograma físico-financeiro.',
      deliverables: ['Projeto executivo', 'Alvará e ART', 'Cronograma fechado'],
    },
    {
      title: 'Fundação',
      duration: '2–4 semanas',
      desc: 'Sondagem do solo, locação da obra e execução da fundação dimensionada pelo engenheiro.',
      deliverables: ['Relatório de sondagem', 'Fotos semanais', 'Controle do concreto'],
    },
    {
      title: 'Estrutura e alvenaria',
      duration: '6–10 semanas',
      desc: 'Pilares, vigas, lajes e fechamento em alvenaria, com inspeção a cada concretagem.',
      deliverables: ['Diário de obra', 'Checklist de qualidade', 'Visitas agendadas'],
    },
    {
      title: 'Instalações',
      duration: '4–6 semanas',
      desc: 'Elétrica, hidráulica, gás e climatização conforme projeto, testadas antes do fechamento.',
      deliverables: ['Testes de estanqueidade', 'As built das instalações', 'Laudos técnicos'],
    },
    {
      title: 'Acabamento e entrega',
      duration: '4–8 semanas',
      desc: 'Revestimentos, pintura, marcenaria e limpeza final. Vistoria com você antes da entrega das chaves.',
      deliverables: ['Vistoria de entrega', 'Manual do proprietário', 'Garantia estrutural de 5 anos'],
    },
  ],
  contactTitle: 'Agende uma visita técnica',
  contactLead: 'Um engenheiro vai até o local, entende o projeto e entrega um orçamento detalhado.',
  name: 'Nome',
  namePlaceholder: 'Seu nome completo',
  city: 'Local da obra',
  cityPlaceholder: 'Ex.: Barra da Tijuca',
  summary: (type: string, area: number) => `Simulação: ${type} · ${area} m²`,
  send: 'Solicitar visita',
  errors: { name: 'Nome é obrigatório.', phone: 'Telefone incompleto.', city: 'Informe o local da obra.' },
  doneTitle: (name: string) => `Pedido enviado, ${name}!`,
  doneText: 'Um engenheiro entra em contato em até 1 dia útil. Este é um demo — nenhuma visita foi agendada.',
  newRequest: 'Novo pedido',
  footerNote: 'CREA-RJ 2012345678 · Responsável técnico: Eng. Ricardo Alves',
  demoBy: 'Demo por MX Studio Web',
};

type AlicerceText = typeof pt;

const en: AlicerceText = {
  tagline: 'Engineering & construction',
  navEstimate: 'Estimate',
  navProjects: 'Projects',
  navStages: 'Stages',
  cta: 'Request a site visit',
  heroEyebrow: 'Construction & renovation · Rio de Janeiro and Niterói',
  heroTitleA: 'We build what you imagine,',
  heroTitleEm: 'on the schedule',
  heroTitleB: 'we promise.',
  heroLead:
    'Homes, renovations and commercial projects with a fixed schedule, a lead engineer and a weekly photo report.',
  simulate: 'Get an estimate',
  seeProjects: 'See finished projects',
  heroAlt: 'Alicerce Engenharia construction site',
  stats: [
    { kpi: '212', label: 'projects delivered' },
    { kpi: '18', label: 'years in business' },
    { kpi: '96%', label: 'delivered on time' },
    { kpi: '100%', label: 'with registered ART' },
  ],
  estimateEyebrow: 'Estimator',
  estimateTitleA: 'How much will',
  estimateTitleEm: 'your project cost',
  estimateLead: 'An initial estimate in seconds. The final price comes after the site visit.',
  typeLabel: 'Project type',
  types: { casa: 'New house', reforma: 'Renovation', ampliacao: 'Extension', comercial: 'Commercial' },
  areaLabel: 'Built area',
  standardLabel: 'Finish level',
  standards: { economico: 'Budget', medio: 'Standard', alto: 'High-end' },
  resultLabel: 'Estimate',
  rangeSeparator: 'to',
  perM2: (v) => `≈ ${v} per m²`,
  durationLabel: 'Estimated timeline',
  months: (n) => `${n} ${n === 1 ? 'month' : 'months'}`,
  estimateNote: 'Reference prices for the Rio de Janeiro metro area. Not a substitute for a technical quote.',
  requestVisit: 'I want a site visit',
  projectsEyebrow: 'Finished projects',
  projectsTitle: 'A portfolio you can go and see.',
  categories: { all: 'All', residencial: 'Residential', comercial: 'Commercial', reforma: 'Renovation' },
  projects: {
    o1: 'Pedra Bonita Residence',
    o2: 'Lapa 12 Office Building',
    o3: 'Cosme Velho House Retrofit',
    o4: 'Jardim Botânico House',
    o5: 'Ipanema Concept Store',
    o6: 'Icaraí Penthouse',
  },
  delivered: (y) => `Delivered in ${y}`,
  stagesEyebrow: 'Construction stages',
  stagesTitleA: 'You follow',
  stagesTitleEm: 'every stage',
  stageOf: (n, total) => `Stage ${n} of ${total}`,
  deliverablesLabel: 'What you get',
  stages: [
    {
      title: 'Design & permits',
      duration: '4–8 weeks',
      desc: 'Site survey, architectural and engineering drawings, city permits and a physical-financial schedule.',
      deliverables: ['Construction drawings', 'Permit and ART', 'Fixed schedule'],
    },
    {
      title: 'Foundation',
      duration: '2–4 weeks',
      desc: 'Soil testing, site layout and a foundation sized by the engineer.',
      deliverables: ['Soil report', 'Weekly photos', 'Concrete quality control'],
    },
    {
      title: 'Structure & masonry',
      duration: '6–10 weeks',
      desc: 'Columns, beams, slabs and masonry walls, with an inspection at every concrete pour.',
      deliverables: ['Site log', 'Quality checklist', 'Scheduled visits'],
    },
    {
      title: 'Building systems',
      duration: '4–6 weeks',
      desc: 'Electrical, plumbing, gas and HVAC per the drawings, tested before walls are closed.',
      deliverables: ['Leak tests', 'As-built drawings', 'Technical reports'],
    },
    {
      title: 'Finishes & handover',
      duration: '4–8 weeks',
      desc: 'Tiling, paint, joinery and final cleaning. A walkthrough with you before handing over the keys.',
      deliverables: ['Handover inspection', "Owner's manual", '5-year structural warranty'],
    },
  ],
  contactTitle: 'Book a site visit',
  contactLead: 'An engineer comes to the site, understands the project and delivers a detailed quote.',
  name: 'Name',
  namePlaceholder: 'Your full name',
  city: 'Project location',
  cityPlaceholder: 'E.g.: Barra da Tijuca',
  summary: (type, area) => `Estimate: ${type} · ${area} m²`,
  send: 'Request visit',
  errors: { name: 'Name is required.', phone: 'Incomplete phone number.', city: 'Tell us where the project is.' },
  doneTitle: (name) => `Request sent, ${name}!`,
  doneText: 'An engineer will contact you within 1 business day. This is a demo — no visit was scheduled.',
  newRequest: 'New request',
  footerNote: 'CREA-RJ 2012345678 · Lead engineer: Ricardo Alves',
  demoBy: 'Demo by MX Studio Web',
};

const es: AlicerceText = {
  tagline: 'Ingeniería y obras',
  navEstimate: 'Presupuesto',
  navProjects: 'Obras',
  navStages: 'Etapas',
  cta: 'Pedir visita técnica',
  heroEyebrow: 'Construcción y reforma · Río de Janeiro y Niterói',
  heroTitleA: 'Construimos lo que imaginas,',
  heroTitleEm: 'en el plazo',
  heroTitleB: 'que prometemos.',
  heroLead:
    'Casas, reformas y obras comerciales con cronograma cerrado, ingeniero responsable e informe semanal con fotos.',
  simulate: 'Simular presupuesto',
  seeProjects: 'Ver obras entregadas',
  heroAlt: 'Obra de Alicerce Engenharia',
  stats: [
    { kpi: '212', label: 'obras entregadas' },
    { kpi: '18', label: 'años en el mercado' },
    { kpi: '96%', label: 'entregadas a tiempo' },
    { kpi: '100%', label: 'con ART registrada' },
  ],
  estimateEyebrow: 'Simulador',
  estimateTitleA: '¿Cuánto cuesta',
  estimateTitleEm: 'tu obra',
  estimateLead: 'Una estimación inicial en segundos. El precio final sale después de la visita técnica.',
  typeLabel: 'Tipo de obra',
  types: { casa: 'Casa nueva', reforma: 'Reforma', ampliacao: 'Ampliación', comercial: 'Comercial' },
  areaLabel: 'Superficie construida',
  standardLabel: 'Nivel de acabado',
  standards: { economico: 'Económico', medio: 'Medio', alto: 'Alta gama' },
  resultLabel: 'Estimación',
  rangeSeparator: 'a',
  perM2: (v) => `≈ ${v} por m²`,
  durationLabel: 'Plazo estimado',
  months: (n) => `${n} ${n === 1 ? 'mes' : 'meses'}`,
  estimateNote: 'Valores de referencia para el área metropolitana de Río. No sustituyen el presupuesto técnico.',
  requestVisit: 'Quiero una visita técnica',
  projectsEyebrow: 'Obras entregadas',
  projectsTitle: 'Un portafolio que puedes visitar.',
  categories: { all: 'Todas', residencial: 'Residencial', comercial: 'Comercial', reforma: 'Reforma' },
  projects: {
    o1: 'Residencia Pedra Bonita',
    o2: 'Edificio Comercial Lapa 12',
    o3: 'Rehabilitación Casa Cosme Velho',
    o4: 'Casa Jardim Botânico',
    o5: 'Tienda concepto Ipanema',
    o6: 'Ático Icaraí',
  },
  delivered: (y) => `Entregada en ${y}`,
  stagesEyebrow: 'Etapas de la obra',
  stagesTitleA: 'Sigues',
  stagesTitleEm: 'cada etapa',
  stageOf: (n, total) => `Etapa ${n} de ${total}`,
  deliverablesLabel: 'Lo que recibes',
  stages: [
    {
      title: 'Proyecto y permisos',
      duration: '4–8 semanas',
      desc: 'Levantamiento, proyecto arquitectónico y de instalaciones, permisos municipales y cronograma físico-financiero.',
      deliverables: ['Proyecto de ejecución', 'Licencia y ART', 'Cronograma cerrado'],
    },
    {
      title: 'Cimentación',
      duration: '2–4 semanas',
      desc: 'Estudio del suelo, replanteo y ejecución de la cimentación calculada por el ingeniero.',
      deliverables: ['Informe geotécnico', 'Fotos semanales', 'Control del hormigón'],
    },
    {
      title: 'Estructura y albañilería',
      duration: '6–10 semanas',
      desc: 'Pilares, vigas, forjados y cerramientos, con inspección en cada hormigonado.',
      deliverables: ['Diario de obra', 'Checklist de calidad', 'Visitas programadas'],
    },
    {
      title: 'Instalaciones',
      duration: '4–6 semanas',
      desc: 'Electricidad, fontanería, gas y climatización según proyecto, probadas antes del cierre.',
      deliverables: ['Pruebas de estanqueidad', 'Planos as built', 'Informes técnicos'],
    },
    {
      title: 'Acabados y entrega',
      duration: '4–8 semanas',
      desc: 'Revestimientos, pintura, carpintería y limpieza final. Revisión contigo antes de entregar las llaves.',
      deliverables: ['Inspección de entrega', 'Manual del propietario', 'Garantía estructural de 5 años'],
    },
  ],
  contactTitle: 'Agenda una visita técnica',
  contactLead: 'Un ingeniero va al lugar, entiende el proyecto y te entrega un presupuesto detallado.',
  name: 'Nombre',
  namePlaceholder: 'Tu nombre completo',
  city: 'Ubicación de la obra',
  cityPlaceholder: 'Ej.: Barra da Tijuca',
  summary: (type, area) => `Simulación: ${type} · ${area} m²`,
  send: 'Solicitar visita',
  errors: { name: 'El nombre es obligatorio.', phone: 'Teléfono incompleto.', city: 'Indica dónde es la obra.' },
  doneTitle: (name) => `¡Solicitud enviada, ${name}!`,
  doneText: 'Un ingeniero te contactará en 1 día hábil. Esto es una demo: no se agendó ninguna visita.',
  newRequest: 'Nueva solicitud',
  footerNote: 'CREA-RJ 2012345678 · Responsable técnico: Ing. Ricardo Alves',
  demoBy: 'Demo por MX Studio Web',
};

export const content: Record<Locale, AlicerceText> = { pt, en, es };
