import type { Locale } from '@/i18n/config';

type Money = (brl: number) => string;

const pt = {
  navAreas: 'Áreas',
  navPartners: 'Sócios',
  navCases: 'Casos',
  startConsult: 'Iniciar consulta',
  heroEyebrow: 'Desde 2008 · Rio de Janeiro',
  heroTitleA: 'Um escritório para quando',
  heroTitleEm: 'a causa importa',
  heroLead:
    'Atuamos em direito empresarial, tributário, trabalhista e cível para empresas e pessoas físicas de alta renda que exigem excelência técnica e presença próxima.',
  seeAreas: 'Ver áreas de atuação',
  stats: [
    { kpi: '17+', label: 'anos de banca' },
    { kpi: '6', label: 'advogados no time' },
    { kpi: '24h', label: 'para primeiro retorno' },
    { kpi: '4', label: 'áreas de atuação' },
  ],
  heroAlt: 'Biblioteca Motta Advogados',
  quote: '"A gente não vende resultado. A gente compromete presença técnica no seu problema."',
  founderRole: 'Sócio-fundador',
  areasEyebrow: 'Áreas de atuação',
  areasTitleA: 'Quatro áreas.',
  areasTitleEm: 'Uma banca.',
  areas: {
    empresarial: {
      name: 'Direito empresarial',
      short: 'Constituição, contratos, disputas.',
      bio: 'Cuidamos da vida jurídica de empresas do porte de PMEs a grupos econômicos. Do contrato societário à disputa comercial complexa.',
      bullets: [
        'Constituição societária e reestruturação',
        'Contratos comerciais e M&A',
        'Recuperação judicial e falências',
        'Compliance e governança',
      ],
      cases: 'Atuação desde 2011',
    },
    tributario: {
      name: 'Tributário',
      short: 'Planejamento e contencioso fiscal.',
      bio: 'Reduzimos a carga tributária dentro da lei e defendemos autuações administrativas e judiciais em todas as instâncias.',
      bullets: [
        'Planejamento tributário',
        'Contencioso administrativo (CARF)',
        'Ações declaratórias e repetição',
        'Consultoria em ICMS, ISS, PIS/COFINS',
      ],
      cases: 'Contencioso administrativo e judicial',
    },
    trabalhista: {
      name: 'Trabalhista',
      short: 'Defesa empresarial e assessoria.',
      bio: 'Assessoria preventiva e defesa em reclamações trabalhistas, com foco na redução de passivos e no compliance da folha.',
      bullets: [
        'Consultoria preventiva',
        'Defesa em reclamações',
        'Acordos individuais e coletivos',
        'Auditoria de folha e riscos',
      ],
      cases: 'Defesa empresarial e prevenção',
    },
    civel: {
      name: 'Cível',
      short: 'Contratos, responsabilidade, imóveis.',
      bio: 'Atuação em disputas cíveis complexas: contratos, responsabilidade civil, imobiliário, sucessões e família de alta renda.',
      bullets: [
        'Contratos e responsabilidade civil',
        'Imobiliário e locações',
        'Família e sucessões',
        'Recuperação de crédito',
      ],
      cases: '17 anos de atuação',
    },
  },
  partnersEyebrow: 'Quem cuida',
  partnersTitleA: 'Os sócios que',
  partnersTitleEm: 'olham o seu caso',
  partnersTitleB: 'no olho.',
  partners: [
    { role: 'Sócio-fundador', area: 'Direito empresarial · Tributário' },
    { role: 'Sócia', area: 'Trabalhista · Cível' },
    { role: 'Sócio', area: 'Tributário · Contencioso' },
  ],
  casesEyebrow: 'Casos-tipo',
  casesTitle: 'Situações reais em que atuamos.',
  cases: [
    { area: 'Tributário', title: 'Repetição de indébito ICMS-ST', scope: 'Levantamento de créditos e ação de repetição' },
    { area: 'Empresarial', title: 'Reestruturação societária', scope: 'Planejamento societário e redação do acordo' },
    { area: 'Trabalhista', title: 'Rescisão de alto valor', scope: 'Negociação e formalização do acordo' },
    { area: 'Cível', title: 'Ação de despejo comercial', scope: 'Ação de despejo e acompanhamento processual' },
    { area: 'Tributário', title: 'Defesa CARF ISS', scope: 'Defesa administrativa perante o CARF' },
    { area: 'Empresarial', title: 'M&A de médio porte', scope: 'Due diligence e assessoria na negociação' },
  ],
  compliance:
    'Em conformidade com o Provimento 205/2021 do CFOAB: esta seção descreve o tipo de atuação, sem divulgação de resultados, valores ou honorários.',
  ctaTitleA: 'Precisa de',
  ctaTitleEm: 'orientação jurídica',
  ctaLead:
    'Consulta inicial confidencial. Respondemos em até 24 horas úteis com uma triagem gratuita e um orçamento se for o caso.',
  ctaButton: 'Iniciar consulta triada',
  close: 'Fechar',
  whatWeDo: 'O que fazemos',
  consultAbout: (area: string) => `Consultar sobre ${area.toLowerCase()}`,
  intakeStep: (step: number) => `Triagem · passo ${step} de 4`,
  step1Title: 'Sobre qual área é a sua dúvida?',
  step1Lead: 'Escolha a que melhor descreve seu caso.',
  step2Title: 'Qual a urgência do seu caso?',
  step2Lead: 'Isso nos ajuda a priorizar a resposta.',
  urgency: [
    { v: 'baixa', l: 'Consultiva · sem prazo', desc: 'Quero entender melhor uma situação.' },
    { v: 'media', l: 'Preventiva · sem crise', desc: 'Estou me organizando pra algo.' },
    { v: 'alta', l: 'Urgente · há prazo', desc: 'Já recebi uma notificação, citação ou ação.' },
  ],
  step3Title: 'Conte brevemente sobre a situação.',
  step3Lead: 'Sem detalhes sensíveis por enquanto — tudo será refinado na consulta.',
  step3Placeholder: (m: Money) =>
    `Ex.: recebi uma notificação de auto de infração ISS, valor aproximado ${m(340000)}, prazo pra defesa em 30 dias…`,
  charCount: (n: number) => `Mínimo 20 caracteres. ${n}/500.`,
  step4Title: 'Como te encontramos?',
  name: 'Nome',
  namePlaceholder: 'Seu nome completo',
  company: 'Empresa (opcional)',
  companyPlaceholder: 'Se for pela empresa',
  email: 'E-mail',
  emailPlaceholder: 'voce@dominio.com',
  receivedTitle: (name: string) => `Recebido, ${name}.`,
  receivedText:
    'Um dos sócios vai avaliar seu caso e responder em até 24h úteis pelo canal escolhido. Este é apenas um demo.',
  areaLabel: 'Área: ',
  urgencyLabel: 'Urgência: ',
  back: 'Voltar',
  continue: 'Continuar',
  sendIntake: 'Enviar triagem',
  errors: {
    area: 'Escolha uma área.',
    urgency: 'Escolha uma opção.',
    detail: 'Descreva com um pouco mais de detalhe.',
    name: 'Nome é obrigatório.',
    email: 'E-mail inválido.',
    phone: 'Telefone incompleto.',
  },
  demoBy: 'Demo por MX Studio',
};

type MottaText = typeof pt;

const en: MottaText = {
  navAreas: 'Practice areas',
  navPartners: 'Partners',
  navCases: 'Cases',
  startConsult: 'Start a consultation',
  heroEyebrow: 'Since 2008 · Rio de Janeiro',
  heroTitleA: 'A law firm for when',
  heroTitleEm: 'the case matters',
  heroLead:
    'We practice corporate, tax, employment and civil law for companies and high-net-worth individuals who demand technical excellence and a hands-on presence.',
  seeAreas: 'See practice areas',
  stats: [
    { kpi: '17+', label: 'years in practice' },
    { kpi: '6', label: 'lawyers on the team' },
    { kpi: '24h', label: 'for a first reply' },
    { kpi: '4', label: 'practice areas' },
  ],
  heroAlt: 'Motta Advogados library',
  quote: '"We don\'t sell outcomes. We commit real technical presence to your problem."',
  founderRole: 'Founding partner',
  areasEyebrow: 'Practice areas',
  areasTitleA: 'Four areas.',
  areasTitleEm: 'One firm.',
  areas: {
    empresarial: {
      name: 'Corporate law',
      short: 'Incorporation, contracts, disputes.',
      bio: 'We handle the legal life of companies, from SMEs to business groups. From shareholder agreements to complex commercial disputes.',
      bullets: [
        'Incorporation and restructuring',
        'Commercial contracts and M&A',
        'Judicial reorganization and bankruptcy',
        'Compliance and governance',
      ],
      cases: 'Practicing since 2011',
    },
    tributario: {
      name: 'Tax',
      short: 'Tax planning and litigation.',
      bio: 'We lawfully reduce the tax burden and defend administrative and judicial assessments at every level.',
      bullets: [
        'Tax planning',
        'Administrative litigation (CARF)',
        'Declaratory actions and tax refunds',
        'Advisory on ICMS, ISS, PIS/COFINS',
      ],
      cases: 'Administrative and judicial litigation',
    },
    trabalhista: {
      name: 'Employment',
      short: 'Employer defense and advisory.',
      bio: 'Preventive advisory and defense in labor claims, focused on reducing liabilities and keeping payroll compliant.',
      bullets: [
        'Preventive advisory',
        'Defense in labor claims',
        'Individual and collective settlements',
        'Payroll and risk audits',
      ],
      cases: 'Employer defense and prevention',
    },
    civel: {
      name: 'Civil',
      short: 'Contracts, liability, real estate.',
      bio: 'Complex civil disputes: contracts, civil liability, real estate, estates and high-net-worth family matters.',
      bullets: [
        'Contracts and civil liability',
        'Real estate and leases',
        'Family and estates',
        'Debt recovery',
      ],
      cases: '17 years of practice',
    },
  },
  partnersEyebrow: 'Who handles your case',
  partnersTitleA: 'The partners who',
  partnersTitleEm: 'look your case',
  partnersTitleB: 'in the eye.',
  partners: [
    { role: 'Founding partner', area: 'Corporate law · Tax' },
    { role: 'Partner', area: 'Employment · Civil' },
    { role: 'Partner', area: 'Tax · Litigation' },
  ],
  casesEyebrow: 'Typical cases',
  casesTitle: 'Real situations we handle.',
  cases: [
    { area: 'Tax', title: 'ICMS-ST tax refund', scope: 'Credit review and refund lawsuit' },
    { area: 'Corporate', title: 'Corporate restructuring', scope: 'Corporate planning and agreement drafting' },
    { area: 'Employment', title: 'High-value termination', scope: 'Negotiation and settlement' },
    { area: 'Civil', title: 'Commercial eviction', scope: 'Eviction lawsuit and case management' },
    { area: 'Tax', title: 'ISS defense before CARF', scope: 'Administrative defense before CARF' },
    { area: 'Corporate', title: 'Mid-market M&A', scope: 'Due diligence and deal advisory' },
  ],
  compliance:
    'In compliance with Brazilian Bar (CFOAB) Provision 205/2021: this section describes the type of work, without disclosing results, amounts or fees.',
  ctaTitleA: 'Need',
  ctaTitleEm: 'legal guidance',
  ctaLead:
    'Confidential initial consultation. We reply within 24 business hours with a free assessment and a quote if applicable.',
  ctaButton: 'Start a guided consultation',
  close: 'Close',
  whatWeDo: 'What we do',
  consultAbout: (area) => `Ask about ${area.toLowerCase()}`,
  intakeStep: (step) => `Intake · step ${step} of 4`,
  step1Title: 'Which area is your question about?',
  step1Lead: 'Choose the one that best describes your case.',
  step2Title: 'How urgent is your case?',
  step2Lead: 'This helps us prioritize our reply.',
  urgency: [
    { v: 'baixa', l: 'Advisory · no deadline', desc: 'I want to better understand a situation.' },
    { v: 'media', l: 'Preventive · no crisis', desc: "I'm getting ready for something." },
    { v: 'alta', l: 'Urgent · deadline running', desc: "I've already received a notice, summons or lawsuit." },
  ],
  step3Title: 'Briefly describe the situation.',
  step3Lead: "No sensitive details for now — we'll go deeper in the consultation.",
  step3Placeholder: (m) =>
    `E.g.: I received an ISS tax assessment notice of roughly ${m(340000)}, with 30 days to file a defense…`,
  charCount: (n) => `Minimum 20 characters. ${n}/500.`,
  step4Title: 'How can we reach you?',
  name: 'Name',
  namePlaceholder: 'Your full name',
  company: 'Company (optional)',
  companyPlaceholder: 'If this is on behalf of a company',
  email: 'Email',
  emailPlaceholder: 'you@domain.com',
  receivedTitle: (name) => `Received, ${name}.`,
  receivedText:
    'One of our partners will review your case and reply within 24 business hours through the channel you chose. This is just a demo.',
  areaLabel: 'Area: ',
  urgencyLabel: 'Urgency: ',
  back: 'Back',
  continue: 'Continue',
  sendIntake: 'Submit',
  errors: {
    area: 'Choose an area.',
    urgency: 'Choose an option.',
    detail: 'Please add a bit more detail.',
    name: 'Name is required.',
    email: 'Invalid email.',
    phone: 'Incomplete phone number.',
  },
  demoBy: 'Demo by MX Studio',
};

const es: MottaText = {
  navAreas: 'Áreas',
  navPartners: 'Socios',
  navCases: 'Casos',
  startConsult: 'Iniciar consulta',
  heroEyebrow: 'Desde 2008 · Río de Janeiro',
  heroTitleA: 'Un despacho para cuando',
  heroTitleEm: 'la causa importa',
  heroLead:
    'Ejercemos derecho mercantil, tributario, laboral y civil para empresas y particulares de alto patrimonio que exigen excelencia técnica y cercanía.',
  seeAreas: 'Ver áreas de práctica',
  stats: [
    { kpi: '17+', label: 'años de ejercicio' },
    { kpi: '6', label: 'abogados en el equipo' },
    { kpi: '24h', label: 'para la primera respuesta' },
    { kpi: '4', label: 'áreas de práctica' },
  ],
  heroAlt: 'Biblioteca de Motta Advogados',
  quote: '"No vendemos resultados. Nos comprometemos con presencia técnica en tu problema."',
  founderRole: 'Socio fundador',
  areasEyebrow: 'Áreas de práctica',
  areasTitleA: 'Cuatro áreas.',
  areasTitleEm: 'Un despacho.',
  areas: {
    empresarial: {
      name: 'Derecho mercantil',
      short: 'Constitución, contratos, disputas.',
      bio: 'Nos ocupamos de la vida jurídica de empresas, desde pymes hasta grupos económicos. Del contrato societario a la disputa comercial compleja.',
      bullets: [
        'Constitución societaria y reestructuración',
        'Contratos comerciales y M&A',
        'Concurso de acreedores y quiebras',
        'Compliance y gobierno corporativo',
      ],
      cases: 'Ejerciendo desde 2011',
    },
    tributario: {
      name: 'Tributario',
      short: 'Planificación y contencioso fiscal.',
      bio: 'Reducimos la carga tributaria dentro de la ley y defendemos liquidaciones en vía administrativa y judicial en todas las instancias.',
      bullets: [
        'Planificación tributaria',
        'Contencioso administrativo (CARF)',
        'Acciones declarativas y devolución de tributos',
        'Asesoría en ICMS, ISS, PIS/COFINS',
      ],
      cases: 'Contencioso administrativo y judicial',
    },
    trabalhista: {
      name: 'Laboral',
      short: 'Defensa empresarial y asesoría.',
      bio: 'Asesoría preventiva y defensa en demandas laborales, con foco en reducir pasivos y en el cumplimiento de la nómina.',
      bullets: [
        'Consultoría preventiva',
        'Defensa en demandas',
        'Acuerdos individuales y colectivos',
        'Auditoría de nómina y riesgos',
      ],
      cases: 'Defensa empresarial y prevención',
    },
    civel: {
      name: 'Civil',
      short: 'Contratos, responsabilidad, inmuebles.',
      bio: 'Actuamos en disputas civiles complejas: contratos, responsabilidad civil, inmobiliario, sucesiones y familia de alto patrimonio.',
      bullets: [
        'Contratos y responsabilidad civil',
        'Inmobiliario y arrendamientos',
        'Familia y sucesiones',
        'Recuperación de créditos',
      ],
      cases: '17 años de ejercicio',
    },
  },
  partnersEyebrow: 'Quién te atiende',
  partnersTitleA: 'Los socios que',
  partnersTitleEm: 'miran tu caso',
  partnersTitleB: 'a los ojos.',
  partners: [
    { role: 'Socio fundador', area: 'Derecho mercantil · Tributario' },
    { role: 'Socia', area: 'Laboral · Civil' },
    { role: 'Socio', area: 'Tributario · Contencioso' },
  ],
  casesEyebrow: 'Casos tipo',
  casesTitle: 'Situaciones reales en las que actuamos.',
  cases: [
    { area: 'Tributario', title: 'Devolución de ICMS-ST', scope: 'Análisis de créditos y acción de devolución' },
    { area: 'Mercantil', title: 'Reestructuración societaria', scope: 'Planificación societaria y redacción del acuerdo' },
    { area: 'Laboral', title: 'Despido de alto valor', scope: 'Negociación y formalización del acuerdo' },
    { area: 'Civil', title: 'Desahucio comercial', scope: 'Acción de desahucio y seguimiento procesal' },
    { area: 'Tributario', title: 'Defensa de ISS ante el CARF', scope: 'Defensa administrativa ante el CARF' },
    { area: 'Mercantil', title: 'M&A de mediana escala', scope: 'Due diligence y asesoría en la negociación' },
  ],
  compliance:
    'Conforme a la Disposición 205/2021 del CFOAB (Colegio de Abogados de Brasil): esta sección describe el tipo de actuación, sin divulgar resultados, importes ni honorarios.',
  ctaTitleA: '¿Necesitas',
  ctaTitleEm: 'orientación jurídica',
  ctaLead:
    'Consulta inicial confidencial. Respondemos en un máximo de 24 horas hábiles con una evaluación gratuita y un presupuesto si procede.',
  ctaButton: 'Iniciar consulta guiada',
  close: 'Cerrar',
  whatWeDo: 'Qué hacemos',
  consultAbout: (area) => `Consultar sobre ${area.toLowerCase()}`,
  intakeStep: (step) => `Evaluación · paso ${step} de 4`,
  step1Title: '¿Sobre qué área es tu consulta?',
  step1Lead: 'Elige la que mejor describe tu caso.',
  step2Title: '¿Qué urgencia tiene tu caso?',
  step2Lead: 'Esto nos ayuda a priorizar la respuesta.',
  urgency: [
    { v: 'baixa', l: 'Consultiva · sin plazo', desc: 'Quiero entender mejor una situación.' },
    { v: 'media', l: 'Preventiva · sin crisis', desc: 'Me estoy preparando para algo.' },
    { v: 'alta', l: 'Urgente · hay plazo', desc: 'Ya recibí una notificación, citación o demanda.' },
  ],
  step3Title: 'Cuéntanos brevemente la situación.',
  step3Lead: 'Sin datos sensibles por ahora: lo afinaremos en la consulta.',
  step3Placeholder: (m) =>
    `Ej.: recibí una notificación de infracción de ISS por unos ${m(340000)}, con 30 días de plazo para la defensa…`,
  charCount: (n) => `Mínimo 20 caracteres. ${n}/500.`,
  step4Title: '¿Cómo te contactamos?',
  name: 'Nombre',
  namePlaceholder: 'Tu nombre completo',
  company: 'Empresa (opcional)',
  companyPlaceholder: 'Si es en nombre de una empresa',
  email: 'Correo electrónico',
  emailPlaceholder: 'tu@dominio.com',
  receivedTitle: (name) => `Recibido, ${name}.`,
  receivedText:
    'Uno de los socios evaluará tu caso y responderá en un máximo de 24 horas hábiles por el canal elegido. Esto es solo una demo.',
  areaLabel: 'Área: ',
  urgencyLabel: 'Urgencia: ',
  back: 'Volver',
  continue: 'Continuar',
  sendIntake: 'Enviar',
  errors: {
    area: 'Elige un área.',
    urgency: 'Elige una opción.',
    detail: 'Describe la situación con un poco más de detalle.',
    name: 'El nombre es obligatorio.',
    email: 'Correo no válido.',
    phone: 'Teléfono incompleto.',
  },
  demoBy: 'Demo por MX Studio',
};

export const content: Record<Locale, MottaText> = { pt, en, es };
