import type { Locale } from '@/i18n/config';

const pt = {
  tagline: 'Imóveis boutique',
  imBroker: 'Sou corretor',
  search: 'Buscar imóvel',
  heroTitleA: 'Imóveis com',
  heroTitleEm: 'alma',
  heroTitleB: ', curados por quem entende de Rio.',
  heroLead: 'Vitrine boutique de propriedades selecionadas na Zona Sul e Barra. Sem enrolação de portal.',
  heroAlt: 'Interior de imóvel curado — Rio de Janeiro',
  searchPlaceholder: 'Buscar por bairro ou tipo de imóvel',
  clear: 'Limpar',
  filters: 'Filtros',
  allNeighborhoods: 'Bairro (todos)',
  allTypes: 'Tipo (todos)',
  anyPrice: 'Faixa de preço (qualquer)',
  upTo: (v: string) => `Até ${v}`,
  above: (v: string) => `Acima de ${v}`,
  count: (n: number) => `${n} ${n === 1 ? 'imóvel' : 'imóveis'}`,
  clearFilters: 'Limpar filtros',
  sort: { novos: 'Novos', menor: '↑ preço', maior: '↓ preço' },
  anyRooms: 'Qualquer quarto',
  roomsPlus: (n: number) => `${n}+ quartos`,
  empty: 'Nenhum imóvel corresponde aos filtros.',
  see: (name: string) => `Ver ${name}`,
  exclusive: 'Exclusivo',
  isNew: 'Novo',
  addWish: 'Adicionar aos favoritos',
  removeWish: 'Remover dos favoritos',
  talk: 'Falar',
  trust: [
    { kpi: '17 anos', label: 'curando imóveis' },
    { kpi: '98%', label: 'satisfação' },
    { kpi: '0', label: 'portais que precisamos' },
    { kpi: '24h', label: 'visita agendada' },
  ],
  close: 'Fechar',
  photoAlt: (i: number, name: string) => `Foto ${i} de ${name}`,
  photoCounter: (i: number, total: number) => `Foto ${i} de ${total}`,
  prevPhoto: 'Foto anterior',
  nextPhoto: 'Próxima foto',
  curated: 'Curadoria Costa Imóveis',
  feesNote: 'IPTU e condomínio inclusos na visita',
  rooms: (n: number) => `${n} ${n === 1 ? 'quarto' : 'quartos'}`,
  baths: (n: number) => `${n} ${n === 1 ? 'banheiro' : 'banheiros'}`,
  description:
    'Imóvel de padrão elevado em rua tranquila, próximo a comércios e bem servido de transporte. Ideal para investidor ou moradia. Documentação em ordem, aceita financiamento e permuta parcial.',
  talkToAgent: 'Falar com quem cuida',
  scheduleVisit: 'Agendar visita',
  types: { Apartamento: 'Apartamento', Cobertura: 'Cobertura', Casa: 'Casa', Loft: 'Loft' },
  properties: {
    i1: 'Cobertura duplex vista mar',
    i2: 'Apartamento reformado',
    i3: 'Loft em pé-direito duplo',
    i4: 'Casa em condomínio',
    i5: 'Apartamento com varanda gourmet',
    i6: 'Cobertura em prédio boutique',
    i7: 'Studio compacto reformado',
    i8: 'Casa de vila',
    i9: 'Apartamento renovado',
    i10: 'Loft industrial',
  },
  demoBy: 'Demo por MX Studio',
};

type CostaText = typeof pt;

const en: CostaText = {
  tagline: 'Boutique real estate',
  imBroker: "I'm an agent",
  search: 'Find a property',
  heroTitleA: 'Homes with',
  heroTitleEm: 'soul',
  heroTitleB: ', curated by people who know Rio.',
  heroLead:
    "A boutique showcase of hand-picked properties in Rio's South Zone and Barra. None of the listing-portal noise.",
  heroAlt: 'Curated home interior — Rio de Janeiro',
  searchPlaceholder: 'Search by neighborhood or property type',
  clear: 'Clear',
  filters: 'Filters',
  allNeighborhoods: 'Neighborhood (all)',
  allTypes: 'Type (all)',
  anyPrice: 'Price range (any)',
  upTo: (v) => `Up to ${v}`,
  above: (v) => `Over ${v}`,
  count: (n) => `${n} ${n === 1 ? 'property' : 'properties'}`,
  clearFilters: 'Clear filters',
  sort: { novos: 'Newest', menor: '↑ price', maior: '↓ price' },
  anyRooms: 'Any bedrooms',
  roomsPlus: (n) => `${n}+ bedrooms`,
  empty: 'No properties match your filters.',
  see: (name) => `View ${name}`,
  exclusive: 'Exclusive',
  isNew: 'New',
  addWish: 'Add to favorites',
  removeWish: 'Remove from favorites',
  talk: 'Chat',
  trust: [
    { kpi: '17 years', label: 'curating homes' },
    { kpi: '98%', label: 'client satisfaction' },
    { kpi: '0', label: 'listing portals needed' },
    { kpi: '24h', label: 'to book a viewing' },
  ],
  close: 'Close',
  photoAlt: (i, name) => `Photo ${i} of ${name}`,
  photoCounter: (i, total) => `Photo ${i} of ${total}`,
  prevPhoto: 'Previous photo',
  nextPhoto: 'Next photo',
  curated: 'Curated by Costa Imóveis',
  feesNote: 'Property tax & condo fees shared at the viewing',
  rooms: (n) => `${n} ${n === 1 ? 'bedroom' : 'bedrooms'}`,
  baths: (n) => `${n} ${n === 1 ? 'bathroom' : 'bathrooms'}`,
  description:
    'High-end property on a quiet street, close to shops and well served by public transport. Ideal for investors or as a home. Paperwork in order; financing and partial trade-ins accepted.',
  talkToAgent: 'Talk to the agent',
  scheduleVisit: 'Book a viewing',
  types: { Apartamento: 'Apartment', Cobertura: 'Penthouse', Casa: 'House', Loft: 'Loft' },
  properties: {
    i1: 'Duplex penthouse with ocean view',
    i2: 'Renovated apartment',
    i3: 'Double-height loft',
    i4: 'House in a gated community',
    i5: 'Apartment with gourmet balcony',
    i6: 'Penthouse in a boutique building',
    i7: 'Compact renovated studio',
    i8: 'Village-lane house',
    i9: 'Updated apartment',
    i10: 'Industrial loft',
  },
  demoBy: 'Demo by MX Studio',
};

const es: CostaText = {
  tagline: 'Inmuebles boutique',
  imBroker: 'Soy agente',
  search: 'Buscar inmueble',
  heroTitleA: 'Inmuebles con',
  heroTitleEm: 'alma',
  heroTitleB: ', seleccionados por quien conoce Río.',
  heroLead: 'Escaparate boutique de propiedades seleccionadas en la Zona Sur y Barra. Sin el ruido de los portales.',
  heroAlt: 'Interior de inmueble seleccionado — Río de Janeiro',
  searchPlaceholder: 'Buscar por barrio o tipo de inmueble',
  clear: 'Borrar',
  filters: 'Filtros',
  allNeighborhoods: 'Barrio (todos)',
  allTypes: 'Tipo (todos)',
  anyPrice: 'Rango de precio (cualquiera)',
  upTo: (v) => `Hasta ${v}`,
  above: (v) => `Más de ${v}`,
  count: (n) => `${n} ${n === 1 ? 'inmueble' : 'inmuebles'}`,
  clearFilters: 'Borrar filtros',
  sort: { novos: 'Nuevos', menor: '↑ precio', maior: '↓ precio' },
  anyRooms: 'Cualquier nº de habitaciones',
  roomsPlus: (n) => `${n}+ habitaciones`,
  empty: 'Ningún inmueble coincide con los filtros.',
  see: (name) => `Ver ${name}`,
  exclusive: 'Exclusivo',
  isNew: 'Nuevo',
  addWish: 'Añadir a favoritos',
  removeWish: 'Quitar de favoritos',
  talk: 'Hablar',
  trust: [
    { kpi: '17 años', label: 'seleccionando inmuebles' },
    { kpi: '98%', label: 'de satisfacción' },
    { kpi: '0', label: 'portales que necesitamos' },
    { kpi: '24h', label: 'para agendar visita' },
  ],
  close: 'Cerrar',
  photoAlt: (i, name) => `Foto ${i} de ${name}`,
  photoCounter: (i, total) => `Foto ${i} de ${total}`,
  prevPhoto: 'Foto anterior',
  nextPhoto: 'Foto siguiente',
  curated: 'Selección de Costa Imóveis',
  feesNote: 'Impuestos y gastos de comunidad informados en la visita',
  rooms: (n) => `${n} ${n === 1 ? 'habitación' : 'habitaciones'}`,
  baths: (n) => `${n} ${n === 1 ? 'baño' : 'baños'}`,
  description:
    'Inmueble de alto nivel en una calle tranquila, cerca de comercios y bien comunicado. Ideal para inversión o vivienda. Documentación en regla; se acepta financiación y permuta parcial.',
  talkToAgent: 'Hablar con el agente',
  scheduleVisit: 'Agendar visita',
  types: { Apartamento: 'Apartamento', Cobertura: 'Ático', Casa: 'Casa', Loft: 'Loft' },
  properties: {
    i1: 'Ático dúplex con vista al mar',
    i2: 'Apartamento reformado',
    i3: 'Loft con doble altura',
    i4: 'Casa en urbanización cerrada',
    i5: 'Apartamento con terraza gourmet',
    i6: 'Ático en edificio boutique',
    i7: 'Estudio compacto reformado',
    i8: 'Casa en pasaje privado',
    i9: 'Apartamento renovado',
    i10: 'Loft industrial',
  },
  demoBy: 'Demo por MX Studio',
};

export const content: Record<Locale, CostaText> = { pt, en, es };
