import type { Locale } from '@/i18n/config';

const pt = {
  clinic: 'Clínica',
  navPros: 'Profissionais',
  navAgenda: 'Agenda',
  navClinic: 'A clínica',
  book: 'Agendar',
  heroEyebrow: 'Psicologia · Nutrição · Rio de Janeiro',
  heroTitleA: 'Cuidado',
  heroTitleEm: 'sereno',
  heroTitleB: ', no seu ritmo.',
  heroLead:
    'Consultório multiprofissional em Botafogo. Atendimento presencial ou online, com agenda transparente e valorização do vínculo.',
  bookVisit: 'Marcar consulta',
  meetPros: 'Conhecer os profissionais',
  badges: [
    { title: 'LGPD', desc: 'by design' },
    { title: 'Botafogo', desc: '& online' },
    { title: 'Sem plano', desc: 'reembolso emitido' },
  ],
  heroAlt: 'Espaço da Clínica Sereno',
  nextAvailable: 'próxima disponibilidade: hoje 14h',
  bookShort: 'Marcar',
  professionals: {
    p1: {
      name: 'Dra. Camila Rezende',
      role: 'Psicóloga · CRP 05/12345',
      bio: 'Abordagem cognitivo-comportamental, foco em ansiedade e transições de vida.',
      approach: 'TCC',
    },
    p2: {
      name: 'Dr. André Vasconcelos',
      role: 'Psicólogo · CRP 05/67890',
      bio: 'Psicanálise. Adultos e casais. Atende desde 2012.',
      approach: 'Psicanálise',
    },
    p3: {
      name: 'Nutri. Beatriz Alves',
      role: 'Nutricionista · CRN 04/54321',
      bio: 'Nutrição comportamental. Sem dieta restritiva, com foco em relação com a comida.',
      approach: 'Nutrição comportamental',
    },
  },
  prosEyebrow: 'Profissionais',
  prosTitle: 'Escolha com quem quer se cuidar.',
  agendaEyebrow: 'Agenda',
  agendaTitle: 'Sua consulta em 3 passos.',
  agendaLead: 'Escolha profissional, data e horário. A confirmação chega no seu WhatsApp em minutos.',
  youChose: 'Você escolheu',
  assurances: [
    'Seus dados são criptografados. Nunca compartilhamos com terceiros.',
    'Lembrete automático 24h antes da consulta.',
    'Cancelamento gratuito até 12h antes.',
  ],
  doneTitle: 'Consulta agendada!',
  doneText: 'Enviamos a confirmação para o WhatsApp. Este é um demo — nada foi realmente agendado.',
  modality: 'Modalidade',
  bookAnother: 'Marcar outra consulta',
  stepDay: '1 · Dia',
  prev: 'Anteriores',
  next: 'Próximos',
  stepTime: '2 · Horário disponível',
  stepModality: '3 · Modalidade',
  modalities: {
    presencial: { label: 'Presencial', desc: 'Consultório em Botafogo' },
    online: { label: 'Online', desc: 'Link Google Meet' },
  },
  fullName: 'Nome completo',
  namePlaceholder: 'Seu nome',
  email: 'E-mail',
  emailPlaceholder: 'voce@dominio.com',
  firstTimeQ: 'Primeira consulta na Sereno?',
  firstYes: 'Sim, primeira vez',
  firstNo: 'Não, já sou paciente',
  consentA: 'Concordo com o tratamento dos meus dados de acordo com a',
  privacyPolicy: 'Política de Privacidade',
  consentB: 'e a LGPD.',
  submit: 'Agendar consulta',
  errors: {
    time: 'Escolha um horário.',
    name: 'Nome é obrigatório.',
    email: 'E-mail inválido.',
    phone: 'Telefone incompleto.',
    firstTime: 'Selecione uma opção.',
    lgpd: 'É necessário concordar para prosseguir.',
  },
  close: 'Fechar',
  reviewTitle: 'Confere sua consulta',
  date: 'Data',
  time: 'Horário',
  change: 'Alterar',
  confirm: 'Confirmar',
  clinicEyebrow: 'A clínica',
  clinicTitle: 'Um espaço para respirar fundo.',
  clinicLead:
    'Casarão restaurado em Botafogo, 4 consultórios acústicos, sala de espera silenciosa, chá e água à disposição.',
  features: [
    { l: '4 consultórios', s: 'acústicos' },
    { l: 'Sala silenciosa', s: 'com jardim' },
    { l: 'Chá & água', s: 'à disposição' },
    { l: 'Wi-Fi + café', s: 'antes da sessão' },
  ],
  whereEyebrow: 'Onde estamos',
  hours: ['Seg–Sex · 8h às 20h', 'Sáb · 8h às 13h'],
  demoBy: 'Demo por MX Studio Web',
};

type ClinicaText = typeof pt;

const en: ClinicaText = {
  clinic: 'Clinic',
  navPros: 'Specialists',
  navAgenda: 'Book',
  navClinic: 'The clinic',
  book: 'Book',
  heroEyebrow: 'Psychology · Nutrition · Rio de Janeiro',
  heroTitleA: 'Care that feels',
  heroTitleEm: 'serene',
  heroTitleB: ', at your own pace.',
  heroLead:
    'A multidisciplinary practice in Botafogo. In-person or online sessions, with a transparent schedule and a focus on the therapeutic bond.',
  bookVisit: 'Book an appointment',
  meetPros: 'Meet our specialists',
  badges: [
    { title: 'LGPD', desc: 'privacy by design' },
    { title: 'Botafogo', desc: '& online' },
    { title: 'No insurance', desc: 'reimbursement receipts' },
  ],
  heroAlt: 'Inside Clínica Sereno',
  nextAvailable: 'next available: today 2pm',
  bookShort: 'Book',
  professionals: {
    p1: {
      name: 'Dr. Camila Rezende',
      role: 'Psychologist · CRP 05/12345',
      bio: 'Cognitive behavioral approach, focused on anxiety and life transitions.',
      approach: 'CBT',
    },
    p2: {
      name: 'Dr. André Vasconcelos',
      role: 'Psychologist · CRP 05/67890',
      bio: 'Psychoanalysis. Adults and couples. In practice since 2012.',
      approach: 'Psychoanalysis',
    },
    p3: {
      name: 'Beatriz Alves, RD',
      role: 'Nutritionist · CRN 04/54321',
      bio: 'Behavioral nutrition. No restrictive diets — the focus is your relationship with food.',
      approach: 'Behavioral nutrition',
    },
  },
  prosEyebrow: 'Specialists',
  prosTitle: 'Choose who you want to care for you.',
  agendaEyebrow: 'Schedule',
  agendaTitle: 'Your appointment in 3 steps.',
  agendaLead: 'Pick a specialist, date and time. Confirmation reaches your WhatsApp within minutes.',
  youChose: 'You chose',
  assurances: [
    'Your data is encrypted. We never share it with third parties.',
    'Automatic reminder 24h before your appointment.',
    'Free cancellation up to 12h before.',
  ],
  doneTitle: 'Appointment booked!',
  doneText: 'We sent the confirmation to your WhatsApp. This is a demo — nothing was actually booked.',
  modality: 'Format',
  bookAnother: 'Book another appointment',
  stepDay: '1 · Day',
  prev: 'Previous',
  next: 'Next',
  stepTime: '2 · Available time',
  stepModality: '3 · Format',
  modalities: {
    presencial: { label: 'In person', desc: 'Office in Botafogo' },
    online: { label: 'Online', desc: 'Google Meet link' },
  },
  fullName: 'Full name',
  namePlaceholder: 'Your name',
  email: 'Email',
  emailPlaceholder: 'you@domain.com',
  firstTimeQ: 'First appointment at Sereno?',
  firstYes: 'Yes, first time',
  firstNo: "No, I'm already a patient",
  consentA: 'I agree to the processing of my data under the',
  privacyPolicy: 'Privacy Policy',
  consentB: "and Brazil's LGPD.",
  submit: 'Book appointment',
  errors: {
    time: 'Pick a time.',
    name: 'Name is required.',
    email: 'Invalid email.',
    phone: 'Incomplete phone number.',
    firstTime: 'Select an option.',
    lgpd: 'You need to agree to continue.',
  },
  close: 'Close',
  reviewTitle: 'Review your appointment',
  date: 'Date',
  time: 'Time',
  change: 'Edit',
  confirm: 'Confirm',
  clinicEyebrow: 'The clinic',
  clinicTitle: 'A space to take a deep breath.',
  clinicLead:
    'A restored mansion in Botafogo: 4 soundproofed rooms, a quiet waiting room, tea and water always available.',
  features: [
    { l: '4 rooms', s: 'soundproofed' },
    { l: 'Quiet room', s: 'with a garden' },
    { l: 'Tea & water', s: 'always available' },
    { l: 'Wi-Fi + coffee', s: 'before your session' },
  ],
  whereEyebrow: 'Where we are',
  hours: ['Mon–Fri · 8am to 8pm', 'Sat · 8am to 1pm'],
  demoBy: 'Demo by MX Studio Web',
};

const es: ClinicaText = {
  clinic: 'Clínica',
  navPros: 'Profesionales',
  navAgenda: 'Agenda',
  navClinic: 'La clínica',
  book: 'Reservar',
  heroEyebrow: 'Psicología · Nutrición · Río de Janeiro',
  heroTitleA: 'Cuidado',
  heroTitleEm: 'sereno',
  heroTitleB: ', a tu ritmo.',
  heroLead:
    'Consultorio multidisciplinar en Botafogo. Atención presencial u online, con agenda transparente y cuidado del vínculo terapéutico.',
  bookVisit: 'Pedir cita',
  meetPros: 'Conocer a los profesionales',
  badges: [
    { title: 'LGPD', desc: 'privacidad desde el diseño' },
    { title: 'Botafogo', desc: 'y online' },
    { title: 'Sin seguro', desc: 'recibo para reembolso' },
  ],
  heroAlt: 'Espacio de la Clínica Sereno',
  nextAvailable: 'próxima disponibilidad: hoy 14h',
  bookShort: 'Reservar',
  professionals: {
    p1: {
      name: 'Dra. Camila Rezende',
      role: 'Psicóloga · CRP 05/12345',
      bio: 'Enfoque cognitivo-conductual, centrado en ansiedad y transiciones vitales.',
      approach: 'TCC',
    },
    p2: {
      name: 'Dr. André Vasconcelos',
      role: 'Psicólogo · CRP 05/67890',
      bio: 'Psicoanálisis. Adultos y parejas. Atiende desde 2012.',
      approach: 'Psicoanálisis',
    },
    p3: {
      name: 'Nut. Beatriz Alves',
      role: 'Nutricionista · CRN 04/54321',
      bio: 'Nutrición conductual. Sin dietas restrictivas, con foco en la relación con la comida.',
      approach: 'Nutrición conductual',
    },
  },
  prosEyebrow: 'Profesionales',
  prosTitle: 'Elige con quién quieres cuidarte.',
  agendaEyebrow: 'Agenda',
  agendaTitle: 'Tu cita en 3 pasos.',
  agendaLead: 'Elige profesional, fecha y hora. La confirmación llega a tu WhatsApp en minutos.',
  youChose: 'Has elegido',
  assurances: [
    'Tus datos están cifrados. Nunca los compartimos con terceros.',
    'Recordatorio automático 24h antes de la cita.',
    'Cancelación gratuita hasta 12h antes.',
  ],
  doneTitle: '¡Cita reservada!',
  doneText: 'Enviamos la confirmación a tu WhatsApp. Esto es una demo: no se reservó nada.',
  modality: 'Modalidad',
  bookAnother: 'Reservar otra cita',
  stepDay: '1 · Día',
  prev: 'Anteriores',
  next: 'Siguientes',
  stepTime: '2 · Horario disponible',
  stepModality: '3 · Modalidad',
  modalities: {
    presencial: { label: 'Presencial', desc: 'Consultorio en Botafogo' },
    online: { label: 'Online', desc: 'Enlace de Google Meet' },
  },
  fullName: 'Nombre completo',
  namePlaceholder: 'Tu nombre',
  email: 'Correo electrónico',
  emailPlaceholder: 'tu@dominio.com',
  firstTimeQ: '¿Primera cita en Sereno?',
  firstYes: 'Sí, es la primera vez',
  firstNo: 'No, ya soy paciente',
  consentA: 'Acepto el tratamiento de mis datos conforme a la',
  privacyPolicy: 'Política de Privacidad',
  consentB: 'y la LGPD de Brasil.',
  submit: 'Reservar cita',
  errors: {
    time: 'Elige un horario.',
    name: 'El nombre es obligatorio.',
    email: 'Correo no válido.',
    phone: 'Teléfono incompleto.',
    firstTime: 'Selecciona una opción.',
    lgpd: 'Debes aceptar para continuar.',
  },
  close: 'Cerrar',
  reviewTitle: 'Revisa tu cita',
  date: 'Fecha',
  time: 'Hora',
  change: 'Cambiar',
  confirm: 'Confirmar',
  clinicEyebrow: 'La clínica',
  clinicTitle: 'Un espacio para respirar hondo.',
  clinicLead:
    'Casona restaurada en Botafogo, 4 consultorios insonorizados, sala de espera silenciosa, té y agua a tu disposición.',
  features: [
    { l: '4 consultorios', s: 'insonorizados' },
    { l: 'Sala silenciosa', s: 'con jardín' },
    { l: 'Té y agua', s: 'a tu disposición' },
    { l: 'Wi-Fi + café', s: 'antes de la sesión' },
  ],
  whereEyebrow: 'Dónde estamos',
  hours: ['Lun–Vie · 8h a 20h', 'Sáb · 8h a 13h'],
  demoBy: 'Demo por MX Studio Web',
};

export const content: Record<Locale, ClinicaText> = { pt, en, es };
