import type { Locale } from '@/i18n/config';

type Money = (brl: number) => string;

const pt = {
  collection: 'Coleção Terra 25',
  searchPlaceholder: 'Buscar em Moda & Arte…',
  searchAria: 'Buscar produtos',
  clear: 'Limpar',
  openCart: (n: number) => `Abrir carrinho com ${n} itens`,
  cart: 'Carrinho',
  heroTitleA: 'Peças autorais para quem',
  heroTitleEm: 'se veste como pensa',
  heroLead: (m: Money) =>
    `Frete grátis acima de ${m(500)}. Parcelamos em até 6× sem juros no cartão ou 5% OFF no PIX à vista.`,
  seeCollection: 'Ver coleção',
  heroAlt: 'Coleção Terra 25 — direção de arte',
  newCollection: 'Coleção nova',
  editorial: 'Editorial · Terra 25',
  editorialLine: 'barro, osso, cera.',
  pieces: (n: number) => `${n} ${n === 1 ? 'peça' : 'peças'}`,
  empty: 'Nada por aqui.',
  clearFilters: 'Limpar filtros',
  addWish: 'Adicionar aos favoritos',
  removeWish: 'Remover dos favoritos',
  isNew: 'Novo',
  seeDetails: (name: string) => `Ver detalhes de ${name}`,
  installments3: '3× de ',
  // Prefix for the full (single-payment) price shown next to the installments on product cards.
  orFull: 'ou ',
  add: 'Adicionar',
  categories: {
    Todos: 'Todos',
    Vestidos: 'Vestidos',
    Blusas: 'Blusas',
    'Calças': 'Calças',
    'Acessórios': 'Acessórios',
  },
  products: {
    v1: 'Vestido Terra',
    v2: 'Vestido Longo Barro',
    v3: 'Vestido Camisa Osso',
    b1: 'Blusa Fluida Areia',
    b2: 'Blusa Cropped Ferrugem',
    b3: 'Camisa Larga Cru',
    c1: 'Calça Wide Argila',
    c2: 'Calça Alfaiataria',
    a1: 'Bolsa Trama Cera',
    a2: 'Colar Prata Bruta',
    a3: 'Chapéu de Palha',
    a4: 'Cinto Couro Tabaco',
  },
  trust: (m: Money) => [
    { title: 'Frete grátis', desc: `acima de ${m(500)}` },
    { title: 'Troca em 30 dias', desc: 'sem burocracia' },
    { title: 'Até 6× sem juros', desc: 'ou 5% no PIX' },
    { title: 'Ateliê no RJ', desc: 'feito por gente que ama' },
  ],
  footerAbout: 'Ateliê de moda autoral no Rio de Janeiro. Peças em pequenas tiragens, feitas com carinho.',
  shop: 'Loja',
  shopLinks: ['Coleção Terra 25', 'Peças icônicas', 'Sob encomenda'],
  contact: 'Contato',
  demoBy: 'Demo por MX Studio Web',
  closeCart: 'Fechar carrinho',
  yourCart: 'Seu carrinho',
  close: 'Fechar',
  emptyCart: 'Carrinho vazio',
  emptyCartText: 'Escolhe uma peça pra começar sua composição.',
  keepShopping: 'Continuar comprando',
  decrease: (name: string) => `Diminuir ${name}`,
  increase: (name: string) => `Aumentar ${name}`,
  remove: (name: string) => `Remover ${name}`,
  couponPlaceholder: 'Cupom (tenta MAX10)',
  couponAria: 'Código de cupom',
  apply: 'Aplicar',
  couponApplied: 'MAX10 aplicado — 10% OFF',
  couponInvalid: 'Cupom inválido.',
  subtotal: 'Subtotal',
  discount: 'Desconto',
  shipping: 'Frete',
  free: 'Grátis',
  total: 'Total',
  goCheckout: 'Ir pro checkout',
  closeDetails: 'Fechar detalhes',
  reviews: '4.9 · 128 avaliações',
  installments6: (value: string) => `ou 6× de ${value} sem juros`,
  productDescription:
    'Peça feita à mão no ateliê do Botafogo, em tiragem limitada. Tecido em algodão pima com toque sedoso.',
  size: 'Tam.',
  sizes: ['P', 'M', 'G', 'GG'],
  addToCart: 'Adicionar ao carrinho',
  closeCheckout: 'Fechar checkout',
  checkout: 'Checkout',
  stepDelivery: '1 · Entrega',
  zip: 'CEP',
  street: 'Rua, número e complemento',
  city: 'Cidade e estado',
  continue: 'Continuar',
  stepPayment: '2 · Pagamento',
  pix: 'PIX à vista',
  pixDesc: '5% OFF · aprovação em segundos',
  card: 'Cartão de crédito',
  cardDesc: 'até 6× sem juros',
  back: 'Voltar',
  finish: 'Finalizar',
  orderDone: 'Pedido feito!',
  orderDoneText: 'Enviamos um e-mail com os detalhes. Este é apenas um demo — nenhum pagamento foi processado.',
};

type ModaArteText = typeof pt;

const en: ModaArteText = {
  collection: 'Terra 25 Collection',
  searchPlaceholder: 'Search Moda & Arte…',
  searchAria: 'Search products',
  clear: 'Clear',
  openCart: (n) => `Open cart with ${n} items`,
  cart: 'Cart',
  heroTitleA: 'Original pieces for people who',
  heroTitleEm: 'dress the way they think',
  heroLead: (m) =>
    `Free shipping over ${m(500)}. Up to 6 interest-free installments on card, or 5% off paying upfront with PIX.`,
  seeCollection: 'Shop the collection',
  heroAlt: 'Terra 25 Collection — art direction',
  newCollection: 'New collection',
  editorial: 'Editorial · Terra 25',
  editorialLine: 'clay, bone, wax.',
  pieces: (n) => `${n} ${n === 1 ? 'piece' : 'pieces'}`,
  empty: 'Nothing here.',
  clearFilters: 'Clear filters',
  addWish: 'Add to favorites',
  removeWish: 'Remove from favorites',
  isNew: 'New',
  seeDetails: (name) => `View details for ${name}`,
  installments3: '3× ',
  orFull: 'or ',
  add: 'Add',
  categories: {
    Todos: 'All',
    Vestidos: 'Dresses',
    Blusas: 'Tops',
    'Calças': 'Pants',
    'Acessórios': 'Accessories',
  },
  products: {
    v1: 'Terra Dress',
    v2: 'Clay Maxi Dress',
    v3: 'Bone Shirt Dress',
    b1: 'Sand Flowy Blouse',
    b2: 'Rust Cropped Top',
    b3: 'Raw Oversized Shirt',
    c1: 'Clay Wide-Leg Pants',
    c2: 'Tailored Trousers',
    a1: 'Wax Woven Bag',
    a2: 'Raw Silver Necklace',
    a3: 'Straw Hat',
    a4: 'Tobacco Leather Belt',
  },
  trust: (m) => [
    { title: 'Free shipping', desc: `over ${m(500)}` },
    { title: '30-day exchanges', desc: 'no hassle' },
    { title: 'Up to 6 installments', desc: 'or 5% off with PIX' },
    { title: 'Atelier in Rio', desc: 'made by people who care' },
  ],
  footerAbout: 'Independent fashion atelier in Rio de Janeiro. Small-batch pieces, made with care.',
  shop: 'Shop',
  shopLinks: ['Terra 25 Collection', 'Signature pieces', 'Made to order'],
  contact: 'Contact',
  demoBy: 'Demo by MX Studio Web',
  closeCart: 'Close cart',
  yourCart: 'Your cart',
  close: 'Close',
  emptyCart: 'Your cart is empty',
  emptyCartText: 'Pick a piece to start your look.',
  keepShopping: 'Keep shopping',
  decrease: (name) => `Decrease ${name}`,
  increase: (name) => `Increase ${name}`,
  remove: (name) => `Remove ${name}`,
  couponPlaceholder: 'Coupon (try MAX10)',
  couponAria: 'Coupon code',
  apply: 'Apply',
  couponApplied: 'MAX10 applied — 10% off',
  couponInvalid: 'Invalid coupon.',
  subtotal: 'Subtotal',
  discount: 'Discount',
  shipping: 'Shipping',
  free: 'Free',
  total: 'Total',
  goCheckout: 'Go to checkout',
  closeDetails: 'Close details',
  reviews: '4.9 · 128 reviews',
  installments6: (value) => `or 6 interest-free payments of ${value}`,
  productDescription:
    'Handmade in our Botafogo atelier in a limited run. Pima cotton with a silky feel.',
  size: 'Size',
  sizes: ['S', 'M', 'L', 'XL'],
  addToCart: 'Add to cart',
  closeCheckout: 'Close checkout',
  checkout: 'Checkout',
  stepDelivery: '1 · Delivery',
  zip: 'ZIP / postal code',
  street: 'Street, number and apt.',
  city: 'City and state',
  continue: 'Continue',
  stepPayment: '2 · Payment',
  pix: 'PIX upfront',
  pixDesc: '5% off · approved in seconds',
  card: 'Credit card',
  cardDesc: 'up to 6 interest-free payments',
  back: 'Back',
  finish: 'Place order',
  orderDone: 'Order placed!',
  orderDoneText: 'We sent you an email with the details. This is just a demo — no payment was processed.',
};

const es: ModaArteText = {
  collection: 'Colección Terra 25',
  searchPlaceholder: 'Buscar en Moda & Arte…',
  searchAria: 'Buscar productos',
  clear: 'Borrar',
  openCart: (n) => `Abrir carrito con ${n} artículos`,
  cart: 'Carrito',
  heroTitleA: 'Piezas de autor para quien',
  heroTitleEm: 'se viste como piensa',
  heroLead: (m) =>
    `Envío gratis a partir de ${m(500)}. Hasta 6 cuotas sin interés con tarjeta o 5% de descuento pagando al contado con PIX.`,
  seeCollection: 'Ver colección',
  heroAlt: 'Colección Terra 25 — dirección de arte',
  newCollection: 'Nueva colección',
  editorial: 'Editorial · Terra 25',
  editorialLine: 'barro, hueso, cera.',
  pieces: (n) => `${n} ${n === 1 ? 'pieza' : 'piezas'}`,
  empty: 'No hay nada por aquí.',
  clearFilters: 'Borrar filtros',
  addWish: 'Añadir a favoritos',
  removeWish: 'Quitar de favoritos',
  isNew: 'Nuevo',
  seeDetails: (name) => `Ver detalles de ${name}`,
  installments3: '3× de ',
  orFull: 'o ',
  add: 'Añadir',
  categories: {
    Todos: 'Todo',
    Vestidos: 'Vestidos',
    Blusas: 'Blusas',
    'Calças': 'Pantalones',
    'Acessórios': 'Accesorios',
  },
  products: {
    v1: 'Vestido Terra',
    v2: 'Vestido Largo Barro',
    v3: 'Vestido Camisero Hueso',
    b1: 'Blusa Fluida Arena',
    b2: 'Top Cropped Óxido',
    b3: 'Camisa Holgada Crudo',
    c1: 'Pantalón Wide Arcilla',
    c2: 'Pantalón Sastre',
    a1: 'Bolso Trenzado Cera',
    a2: 'Collar Plata Bruta',
    a3: 'Sombrero de Paja',
    a4: 'Cinturón Cuero Tabaco',
  },
  trust: (m) => [
    { title: 'Envío gratis', desc: `a partir de ${m(500)}` },
    { title: 'Cambios en 30 días', desc: 'sin complicaciones' },
    { title: 'Hasta 6 cuotas', desc: 'o 5% con PIX' },
    { title: 'Taller en Río', desc: 'hecho con cariño' },
  ],
  footerAbout: 'Taller de moda de autor en Río de Janeiro. Piezas en tiradas pequeñas, hechas con cariño.',
  shop: 'Tienda',
  shopLinks: ['Colección Terra 25', 'Piezas icónicas', 'Por encargo'],
  contact: 'Contacto',
  demoBy: 'Demo por MX Studio Web',
  closeCart: 'Cerrar carrito',
  yourCart: 'Tu carrito',
  close: 'Cerrar',
  emptyCart: 'Carrito vacío',
  emptyCartText: 'Elige una pieza para empezar tu look.',
  keepShopping: 'Seguir comprando',
  decrease: (name) => `Reducir ${name}`,
  increase: (name) => `Aumentar ${name}`,
  remove: (name) => `Quitar ${name}`,
  couponPlaceholder: 'Cupón (prueba MAX10)',
  couponAria: 'Código de cupón',
  apply: 'Aplicar',
  couponApplied: 'MAX10 aplicado — 10% de descuento',
  couponInvalid: 'Cupón no válido.',
  subtotal: 'Subtotal',
  discount: 'Descuento',
  shipping: 'Envío',
  free: 'Gratis',
  total: 'Total',
  goCheckout: 'Ir a pagar',
  closeDetails: 'Cerrar detalles',
  reviews: '4.9 · 128 valoraciones',
  installments6: (value) => `o 6 cuotas de ${value} sin interés`,
  productDescription:
    'Pieza hecha a mano en nuestro taller de Botafogo, en tirada limitada. Algodón pima de tacto sedoso.',
  size: 'Talla',
  sizes: ['S', 'M', 'L', 'XL'],
  addToCart: 'Añadir al carrito',
  closeCheckout: 'Cerrar pago',
  checkout: 'Pago',
  stepDelivery: '1 · Envío',
  zip: 'Código postal',
  street: 'Calle, número y piso',
  city: 'Ciudad y provincia',
  continue: 'Continuar',
  stepPayment: '2 · Pago',
  pix: 'PIX al contado',
  pixDesc: '5% de descuento · aprobación en segundos',
  card: 'Tarjeta de crédito',
  cardDesc: 'hasta 6 cuotas sin interés',
  back: 'Volver',
  finish: 'Finalizar',
  orderDone: '¡Pedido realizado!',
  orderDoneText: 'Te enviamos un correo con los detalles. Esto es solo una demo: no se procesó ningún pago.',
};

export const content: Record<Locale, ModaArteText> = { pt, en, es };
